version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.9
    commands:
      - pip install -U pip
      # Use the latest version
      - pip install -U awscli
      # for Lambda
      - pip install -U aws-sam-cli
      - pip install -U boto3
      # for Lambda Powertools
      - pip install -U aws-lambda-powertools
      # CFn Lint
      - pip install -U cfn-lint
  pre_build:
    commands:
      - find ./ -type f -name "*.yaml" | xargs -r cfn-lint --regions ALL_REGIONS
  build:
    commands:
       - sam validate --template ${TEMPLATE_FILE_PATH}template.yaml
       - sam build --template ${TEMPLATE_FILE_PATH}template.yaml
       - sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml