version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.9
    commands:
      - pip install -U pip
      # Use the latest version
      - pip install awscli
      # for Lambda
      - pip install aws-sam-cli
      - pip install boto3
      # for Lambda Powertools
      - pip install aws-lambda-powertools
      # CloudFormation Linter
      - pip install cfn-lint
  pre_build:
    commands:
      - find ./ -type f -name "*.yaml" | xargs --no-run-if-empty cfn-lint --regions ALL_REGIONS
      - sam validate --template ${TEMPLATE_FILE_PATH}template.yaml
  build:
    commands:
      - sam build --template ${TEMPLATE_FILE_PATH}template.yaml
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml