version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - pip install -U pip
      - pip install -U aws-sam-cli
      - pip install -U cfn-lint
      - pip install -U requests
      - pip install -U aws_xray_sdk
  pre_build:
    commands:
      - cfn-lint -t ${TEMPLATE_FILE_PATH}template.yaml
  build:
    commands:
       - sam build --template ${TEMPLATE_FILE_PATH}template.yaml
       - sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml