version: 0.2

env:
  variables:
    AMPLIFY_SRC_DIR: amplify/templates
    AMPLIFY_DIST_DIR: aws-cloudformation-templates/amplify
    CICD_SRC_DIR: cicd/templates
    CICD_DIST_DIR: aws-cloudformation-templates/cicd
    GLOBAL_SRC_DIR: global/templates
    GLOBAL_DIST_DIR: aws-cloudformation-templates/global
    MONITORING_SRC_DIR: monitoring/sam-app
    MONITORING_DIST_DIR: aws-cloudformation-templates/monitoring
    NOTIFICATION_SAM_SRC_DIR: notification/sam-app
    NOTIFICATION_CFN_SRC_DIR: notification/templates
    NOTIFICATION_DIST_DIR: aws-cloudformation-templates/notification
    SECURITY_SRC_DIR: security/templates
    SECURITY_DIST_DIR: aws-cloudformation-templates/security
    SECURITY_CONFIG_RULES_SRC_DIR: security-config-rules/sam-app
    SECURITY_CONFIG_RULES_DIST_DIR: aws-cloudformation-templates/security-config-rules
    HOSTING_SRC_DIR: static-website-hosting-with-ssl/templates
    HOSTING_DIST_DIR: aws-cloudformation-templates/static-website-hosting-with-ssl
    EC2_SRC_DIR: web-servers/templates
    EC2_DIST_DIR: aws-cloudformation-templates/web-servers

phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - pip install -U pip
      - pip install -U aws-sam-cli
      - pip install -U cfn-lint
      - pip install -U requests
      - pip install -U aws_xray_sdk
  pre_build:
    commands:
      - cfn-lint -t ${AMPLIFY_SRC_DIR}/template.yaml
      - cfn-lint -t ${CICD_SRC_DIR}/template.yaml
      - cfn-lint -t ${CICD_SRC_DIR}/codebuild.yaml
      - cfn-lint -t ${GLOBAL_SRC_DIR}/template.yaml
      - cfn-lint -t ${NOTIFICATION_SAM_SRC_DIR}/template.yaml
      - cfn-lint -t ${NOTIFICATION_SAM_SRC_DIR}/sns.yaml
      - cfn-lint -t ${NOTIFICATION_SAM_SRC_DIR}/events.yaml
      - cfn-lint -t ${NOTIFICATION_CFN_SRC_DIR}/chatbot.yaml
      - cfn-lint -t ${SECURITY_SRC_DIR}/template.yaml
      - cfn-lint -t ${SECURITY_CONFIG_RULES_SRC_DIR}/template.yaml
      - cfn-lint -t ${HOSTING_SRC_DIR}/template.yaml
      - cfn-lint -t ${EC2_SRC_DIR}/template.yaml
      - aws s3 rm s3://${BUCKET_NAME}/${AMPLIFY_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${CICD_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${GLOBAL_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${MONITORING_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${NOTIFICATION_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${SECURITY_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${SECURITY_CONFIG_RULES_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${HOSTING_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${EC2_DIST_DIR}/ --recursive
  build:
    commands:
      - sam validate --template ${CICD_SRC_DIR}/template.yaml
      - sam build --template ${CICD_SRC_DIR}/template.yaml --build-dir ${CICD_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${CICD_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${CICD_DIST_DIR} --output-template-file ${CICD_SRC_DIR}/packaged.yaml
      - sam validate --template ${NOTIFICATION_SAM_SRC_DIR}/template.yaml
      - sam build --template ${NOTIFICATION_SAM_SRC_DIR}/template.yaml --build-dir ${NOTIFICATION_SAM_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${NOTIFICATION_SAM_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${NOTIFICATION_DIST_DIR} --output-template-file ${NOTIFICATION_SAM_SRC_DIR}/packaged.yaml
      - sam validate --template ${SECURITY_CONFIG_RULES_SRC_DIR}/template.yaml
      - sam build --template ${SECURITY_CONFIG_RULES_SRC_DIR}/template.yaml --build-dir ${SECURITY_CONFIG_RULES_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${SECURITY_CONFIG_RULES_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${SECURITY_CONFIG_RULES_DIST_DIR} --output-template-file ${SECURITY_CONFIG_RULES_SRC_DIR}/packaged.yaml
      - aws cloudformation package --template-file ${EC2_SRC_DIR}/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${EC2_DIST_DIR} --output-template-file ${EC2_SRC_DIR}/packaged.yaml
  post_build:
    commands:
       - aws s3 cp ${AMPLIFY_SRC_DIR}/ s3://${BUCKET_NAME}/${AMPLIFY_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${CICD_SRC_DIR}/ s3://${BUCKET_NAME}/${CICD_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${GLOBAL_SRC_DIR}/ s3://${BUCKET_NAME}/${GLOBAL_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${MONITORING_SRC_DIR}/ s3://${BUCKET_NAME}/${MONITORING_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${NOTIFICATION_SAM_SRC_DIR}/ s3://${BUCKET_NAME}/${NOTIFICATION_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${NOTIFICATION_CFN_SRC_DIR}/ s3://${BUCKET_NAME}/${NOTIFICATION_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${SECURITY_SRC_DIR}/ s3://${BUCKET_NAME}/${SECURITY_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${SECURITY_CONFIG_RULES_SRC_DIR}/ s3://${BUCKET_NAME}/${SECURITY_CONFIG_RULES_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${HOSTING_SRC_DIR}/ s3://${BUCKET_NAME}/${HOSTING_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'
       - aws s3 cp ${EC2_SRC_DIR}/ s3://${BUCKET_NAME}/${EC2_DIST_DIR}/ --recursive --exclude '*' --include '*.yaml'