AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/network sets basic configurations for network.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Egress Configuration'
        Parameters: 
          - VPCCidrBlockForEgress
          - PublicCidrBlockForEgressAz1
          - PublicCidrBlockForEgressAz2
          - PublicCidrBlockForEgressAz3
          - TransitCidrBlockForEgressAz1
          - TransitCidrBlockForEgressAz2
          - TransitCidrBlockForEgressAz3
          - FirewallCidrBlockForEgressAz1
          - FirewallCidrBlockForEgressAz2
          - FirewallCidrBlockForEgressAz3
      - Label: 
          default: 'DNS Configuration'
        Parameters: 
          - VPCCidrBlockForDNS
          - PrivateCidrBlockForDNSAz1
          - PrivateCidrBlockForDNSAz2
          - PrivateCidrBlockForDNSAz3
          - TransitCidrBlockForDNSAz1
          - TransitCidrBlockForDNSAz2
          - TransitCidrBlockForDNSAz3
      - Label: 
          default: 'VPN Configuration'
        Parameters: 
          - CustomerGatewayOutsideIpAddress
      - Label: 
          default: 'IPAM Configuration'
        Parameters: 
          - HomeNetworkCidr
      - Label: 
          default: 'Route 53 Configuration'
        Parameters: 
          - DnsIpAz1
          - DnsIpAz2
          - DnsIpAz3
          - DomainName
      - Label: 
          default: 'Organizations Configuration'
        Parameters: 
          - ManagementAccountId
          - OrganizationId
      - Label: 
          default: 'Logging Configuration'
        Parameters: 
          - CentralizedLogBucketName
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment 
          - TagKey
          - TagValue

Parameters:
  CentralizedLogBucketName:
    Type: String
    Default: ''
    Description: The centralize S3 bucket name for logging 
  CustomerGatewayOutsideIpAddress:
    Type: String
    Default: ''
    Description: The Internet-routable IP address for the customer gateway's outside interface
  DnsIpAz1:
    Type: String
    Default: 10.0.8.53
    Description: The IPv4 address that you want to use for DNS queries
  DnsIpAz2:
    Type: String
    Default: 10.0.10.53
    Description: The IPv4 address that you want to use for DNS queries
  DnsIpAz3:
    Type: String
    Default: 10.0.12.53
    Description: The IPv4 address that you want to use for DNS queries
  DomainName:
    Type: String
    Default: ''
    Description: The private domain name which this VPC has
  FirewallCidrBlockForEgressAz1:
    Type: String
    Default: 10.0.0.128/26
    Description: The firewall subnet CIDR block for Egress at AZ1
  FirewallCidrBlockForEgressAz2:
    Type: String
    Default: 10.0.2.128/26
    Description: The firewall subnet CIDR block for Egress at AZ2
  FirewallCidrBlockForEgressAz3:
    Type: String
    Default: 10.0.4.128/26
    Description: The firewall subnet CIDR block for Egress at AZ3
  HomeNetworkCidr:
    Type: String
    Default: 10.0.0.0/8
    AllowedPattern: ^[0-9./]*$
    Description: The CIDR of your home network  [required]
  ManagementAccountId:
    Type: String
    Default: ''
    Description: The management account ID
  OnpremDnsIp:
    Type: String
    Default: ''
    Description: One IPv4 address that you want to forward DNS queries to
  OrganizationId:
    Type: String
    Default: ''
    Description: The Organizations ID
  PrivateCidrBlockForDNSAz1:
    Type: String
    Default: 10.0.8.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block for DNS at AZ1 [required]
  PrivateCidrBlockForDNSAz2:
    Type: String
    Default: 10.0.10.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block for DNS at AZ2 [required]
  PrivateCidrBlockForDNSAz3:
    Type: String
    Default: 10.0.12.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block for DNS at AZ3 [required]
  PublicCidrBlockForEgressAz1:
    Type: String
    Default: 10.0.0.0/26
    AllowedPattern: ^[0-9./]*$
    Description: The public subnet CIDR block for Egress at AZ1 [required]
  PublicCidrBlockForEgressAz2:
    Type: String
    Default: 10.0.2.0/26
    AllowedPattern: ^[0-9./]*$
    Description: The public subnet CIDR block for Egress at AZ2 [required]
  PublicCidrBlockForEgressAz3:
    Type: String
    Default: 10.0.4.0/26
    AllowedPattern: ^[0-9./]*$
    Description: The public subnet CIDR block for Egress at AZ3 [required]
  TransitCidrBlockForEgressAz1:
    Type: String
    Default: 10.0.0.64/26
    AllowedPattern: ^[0-9./]*$
    Description: The transit subnet CIDR block for Egress at AZ1 [required]
  TransitCidrBlockForEgressAz2:
    Type: String
    Default: 10.0.2.64/26
    AllowedPattern: ^[0-9./]*$
    Description: The transit subnet CIDR block for Egress at AZ2 [required]
  TransitCidrBlockForEgressAz3:
    Type: String
    Default: 10.0.4.64/26
    AllowedPattern: ^[0-9./]*$
    Description: The transit subnet CIDR block for Egress at AZ3 [required]
  TransitCidrBlockForDNSAz1:
    Type: String
    Default: 10.0.11.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The transit subnet CIDR block for DNS at AZ1 [required]
  TransitCidrBlockForDNSAz2:
    Type: String
    Default: 10.0.13.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The transit subnet CIDR block for DNS at AZ2 [required]
  TransitCidrBlockForDNSAz3:
    Type: String
    Default: 10.0.15.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The transit subnet CIDR block for DNS at AZ3 [required]
  TransitGatewayDestinationCidrBlock:
    Type: String
    Default: ''
    Description: The IPv4 CIDR block forward to TransitGateway
  TransitGatewayDefaultRouteTableId:
    Type: String
    Default: ''
    Description: The id of the default Transit Gateway Route Table
  VPCCidrBlockForEgress:
    Type: String
    Default: 10.0.0.0/21
    AllowedPattern: ^[0-9./]*$
    Description: The VPC CIDR block [required]
  VPCCidrBlockForDNS:
    Type: String
    Default: 10.0.8.0/21
    AllowedPattern: ^[0-9./]*$
    Description: The VPC CIDR block [required]
  SNSForAlertArn:
    Type: String
    Default: '' 
  SNSForDeploymentArn:
    Type: String
    Default: ''
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateRoute53Resolver: !And [ !Not [ !Equals [ !Ref DnsIpAz1, ''] ], !Not [ !Equals [ !Ref DnsIpAz2, ''] ], !Not [ !Equals [ !Ref DnsIpAz3, ''] ], !Not [ !Equals [ !Ref DomainName, ''] ], !Not [ !Equals [ !Ref OnpremDnsIp, ''] ], !Not [ !Equals [ !Ref ManagementAccountId, ''] ], !Not [ !Equals [ !Ref OrganizationId, ''] ] ]
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']
  CreateVPN: !Not [ !Equals [ !Ref CustomerGatewayOutsideIpAddress, ''] ]
  Development: !Equals [ !Ref Environment, development]

Resources:
  Egress:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters: 
        CentralizedLogBucketName: !Ref CentralizedLogBucketName
        HomeNetworkCidr: !Ref HomeNetworkCidr
        LogicalName: Egress
        ResolverInboundRuleId: ''
        ResolverOutboundRuleId: ''
        SubnetPublicCidrBlockForAz1: !Ref PublicCidrBlockForEgressAz1
        SubnetTransitCidrBlockForAz1: !Ref TransitCidrBlockForEgressAz1
        SubnetFirewallCidrBlockForAz1: !Ref FirewallCidrBlockForEgressAz1
        SubnetPublicCidrBlockForAz2: !Ref PublicCidrBlockForEgressAz2
        SubnetTransitCidrBlockForAz2: !Ref TransitCidrBlockForEgressAz2
        SubnetFirewallCidrBlockForAz2: !Ref FirewallCidrBlockForEgressAz2
        SubnetPublicCidrBlockForAz3: !Ref PublicCidrBlockForEgressAz3
        SubnetTransitCidrBlockForAz3: !Ref TransitCidrBlockForEgressAz3
        SubnetFirewallCidrBlockForAz3: !Ref FirewallCidrBlockForEgressAz3
        TransitGatewayDestinationCidrBlock: !Ref TransitGatewayDestinationCidrBlock
        TransitGatewayDefaultRouteTableId: !Ref TransitGatewayDefaultRouteTableId
        TransitGatewayId: !GetAtt TransitGateway.Outputs.TransitGatewayId
        VPCCidrBlock: !Ref VPCCidrBlockForEgress
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn 
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/network/egress.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/network/egress.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  TransitGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters: 
        PrincipalsToAssociateWithTransitGateway: !Sub arn:aws:organizations::${ManagementAccountId}:organization/${OrganizationId}
        LogicalName: !Ref AWS::StackName
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn 
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/network/transitgateway.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/network/transitgateway.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  Route53Resolver:
    Condition: CreateRoute53Resolver
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        DnsIpAz1: !Ref DnsIpAz1
        DnsIpAz2: !Ref DnsIpAz2
        DnsIpAz3: !Ref DnsIpAz3
        LogicalName: Route53Resolver
        OnpremDnsIp: !Ref OnpremDnsIp
        DomainName: !Ref DomainName
        PrincipalsToAssociateWithRoute53ResolverRule: !Sub arn:aws:organizations::${ManagementAccountId}:organization/${OrganizationId}
        SubnetPrivateCidrBlockForAz1: !Ref PrivateCidrBlockForDNSAz1
        SubnetPrivateCidrBlockForAz2: !Ref PrivateCidrBlockForDNSAz2
        SubnetPrivateCidrBlockForAz3: !Ref PrivateCidrBlockForDNSAz3
        SubnetTransitCidrBlockForAz1: !Ref TransitCidrBlockForDNSAz1
        SubnetTransitCidrBlockForAz2: !Ref TransitCidrBlockForDNSAz2
        SubnetTransitCidrBlockForAz3: !Ref TransitCidrBlockForDNSAz3
        TransitGatewayId: !GetAtt TransitGateway.Outputs.TransitGatewayId
        VPCCidrBlock: !Ref VPCCidrBlockForDNS
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn 
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/network/route53resolver.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/network/route53resolver.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  VPN:
    Condition: CreateVPN
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        CustomerGatewayOutsideIpAddress: !Ref CustomerGatewayOutsideIpAddress
        TransitGatewayId: !GetAtt TransitGateway.Outputs.TransitGatewayId
        Environment: !Ref Environment
        LogicalName: !Ref AWS::StackName
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/network/vpn.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/network/vpn.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
    
  # IPAM
  IPAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        PrincipalsToAssociateWithIPAM: !Sub arn:aws:organizations::${ManagementAccountId}:organization/${OrganizationId}
        ProvisionedCidrs: !Ref HomeNetworkCidr
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/network/ipam.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/network/ipam.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue  
  # Network Access Analyzer
  NetworkAccessAnalyzer:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/network/networkaccessanalyzer.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/network/networkaccessanalyzer.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue    
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.7
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.7
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

Outputs:
  TransitGatewayId:
    Description: Transit Gateway Id
    Value: !GetAtt TransitGateway.Outputs.TransitGatewayId