AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/network/transitgateway creates an Transit Gateway.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'RAM Configuration'
        Parameters:
          - PrincipalsToAssociateWithTransitGateway
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment
          - LogicalNamePrefix
          - TagKey
          - TagValue

Parameters:
  PrincipalsToAssociateWithTransitGateway:
    Type: String
    Default: ''
    Description: Specifies a list of one or more principals to associate with Transit Gateway.
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  LogicalNamePrefix:
    Type: String
    Default: TransitGateway
    AllowedPattern: .+
    Description: The custom prefix name [required]
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateRAMForTransitGateway: !Not [ !Equals [ !Ref PrincipalsToAssociateWithTransitGateway, ''] ]

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties: 
      AmazonSideAsn: 64512
      # Enable automatic acceptance of attachment requests.
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      Description: !Sub Transit Gateway created by ${AWS::StackName}
      DnsSupport: enable
      MulticastSupport: enable
      Tags:
        - Key: Name
          Value: !Sub tgw-${LogicalNamePrefix}-${AWS::Region}
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VpnEcmpSupport: enable
  RAMForTransitGateway:
    Condition: CreateRAMForTransitGateway
    Type: AWS::RAM::ResourceShare
    Properties: 
      AllowExternalPrincipals: false
      Name: TransitGateway
      PermissionArns: 
        - arn:aws:ram::aws:permission/AWSRAMDefaultPermissionTransitGateway
      Principals: 
        - !Ref PrincipalsToAssociateWithTransitGateway
      ResourceArns: 
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${TransitGateway}
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

Outputs:
  TransitGatewayId:
    Description: Transit Gateway Id
    Value: !Ref TransitGateway