AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: aws-cloudformation-templates/global creates global settings on N.Virginia Region.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Certificate Manager Configuration'
        Parameters: 
          - ACMValidationMethod
          - ACMDomainName
          - DomainName
      - Label: 
          default: 'Billing Configuration'
        Parameters: 
          - BillingAlertThreshold
          - BudgetName
          - CostUsageReport
          - NotificationThreshold
      - Label: 
          default: 'CloudFront Alarm Configuration'
        Parameters: 
          - CloudFrontErrorRateThreshold
          - CloudFrontErrorRequestPerMinuteThreshold
          - CloudFrontBytesDownloadedPerMinuteThreshold
          - CloudFrontDistributionId
      - Label: 
          default: 'Web ACL Configuration'
        Parameters:
          - WebACL
      - Label: 
          default: 'Logging Configuration'
        Parameters: 
          - CentralizedLogBucketName
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - AlarmLevel
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment
          - TagKey
          - TagValue

Parameters:
  ACMValidationMethod:
    Type: String
    Default: DNS
    AllowedValues:
      - DNS
      - EMAIL
    Description: The validation method that you own or control the domain [required]
  ACMDomainName:
    Type: String
    Default: ''
    Description: The domain name created by Certification Manager
  AlarmLevel:
    Type: String
    Default: NOTICE
    AllowedValues:
      - NOTICE
      - WARNING
    Description: The alarm level of CloudWatch alarms
  BillingAlertThreshold:
    Type: Number
    Default: 0
    MinValue: 0
    Description: CloudWatch alarm threshold about Billing [required]
  BudgetName:
    Type: String
    Default: Total
    AllowedPattern: .+  
    Description: The budget name [required]
  CentralizedLogBucketName:
    Type: String
    Default: ''
    Description: The centralize S3 bucket name for logging 
  CloudFrontErrorRateThreshold:
    Type: Number
    Default: 0
    MinValue: 0
    Description: CloudWatch alarm threshold about CloudFront ErrorRate [required]
  CloudFrontErrorRequestPerMinuteThreshold:
    Type: Number
    Default: 0
    MinValue: 0
    Description: CloudWatch alarm threshold about CloudFront ErrorRequestPerMinute [required]
  CloudFrontBytesDownloadedPerMinuteThreshold:
    Type: Number
    Default: 0
    MinValue: 0
    Description: CloudWatch alarm threshold about CloudFront BytesDownloadedPerMinute [required]
  CloudFrontDistributionId:
    Type: String
    Default: ''
    Description: The target distribution ID monitored by CloudWatch Alarm
  CostUsageReport:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable AWS Config [required]
  DomainName:
    Type: String
    Default: ''
    Description: The name of the domain
  NotificationThreshold:
    Type: Number
    Default: 10
    Description: The dollar value that triggers a notification if the threshold is exceeded [required]
  WebACL:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable WebACL [required]
  SNSForAlertArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for deployment information
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateACMCertificate: !Not [ !Equals [ !Ref ACMDomainName, '' ] ]
  CreateCostUsageReport: !Equals [ !Ref CostUsageReport, ENABLED]
  CreateSNSForAlertTransfer: !Not [ !Equals [ !Ref SNSForAlertArn, ''] ]
  CreateSNSForDeploymentTransfer: !Not [ !Equals [ !Ref SNSForDeploymentArn, ''] ]
  CreateBudget: !Not [ !Equals [ !Ref BillingAlertThreshold, 0 ] ]
  CreateCloudWatchAlarmBilling: !Not [ !Equals [ !Ref BillingAlertThreshold, 0 ] ]
  CreateCloudWatchAlarmCloudFrontErrorRate: !And [ !Not [ !Equals [ !Ref CloudFrontErrorRateThreshold, 0 ] ], !Not [ !Equals [ !Ref CloudFrontDistributionId, ''] ] ]
  CreateCloudWatchAlarmCloudFrontRequests: !And [ !Not [ !Equals [ !Ref CloudFrontErrorRequestPerMinuteThreshold, 0 ] ], !Not [ !Equals [ !Ref CloudFrontDistributionId, ''] ] ]
  CreateCloudWatchAlarmCloudFrontBytesDownloaded: !And [ !Not [ !Equals [ !Ref CloudFrontBytesDownloadedPerMinuteThreshold, 0 ] ], !Not [ !Equals [ !Ref CloudFrontDistributionId, ''] ] ]
  CreateRoute53: !Not [ !Equals [ !Ref DomainName, '' ] ]
  CreateWebACL: !Equals [ !Ref WebACL, ENABLED ]
  Development: !Equals [ !Ref Environment, development]

Resources:
  # Nested Stack
  WAF:
    Condition: CreateWebACL
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CentralizedLogBucketName: !Ref CentralizedLogBucketName
        LogicalName: !Ref AWS::StackName
        Scope: CLOUDFRONT
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue 
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/edge/waf.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/edge/waf.yaml
  CostExplorer:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NotificationThreshold: !Ref NotificationThreshold
        SNSForAlertArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/global/costexplorer.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/global/costexplorer.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CUR:
    Condition: CreateCostUsageReport
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/global/cur.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/global/cur.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  SNSForAlert:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.14
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.14
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  TransferAlertTopic:
    Condition: CreateSNSForAlertTransfer
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeploymentTransfer
          - !Ref SNSForDeploymentArn
          - !Ref AWS::NoValue
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        SourceSNSArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        DestinationSNSArn: !Ref SNSForAlertArn
        Environment: !Ref Environment
        LogicalName: TransferAlertTopic
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/notification/transfer-sns-topic.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/security/transfer-sns-topic.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  TransferDeploymentTopic:
    Condition: CreateSNSForDeploymentTransfer
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !Ref SNSForDeploymentArn
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        SourceSNSArn: !GetAtt SNSForDeployment.Outputs.SNSTopicArn
        DestinationSNSArn: !Ref SNSForDeploymentArn
        Environment: !Ref Environment
        LogicalName: TransferDeploymentTopic
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/notification/transfer-sns-topic.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/security/transfer-sns-topic.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # Budget 
  Budget:
    Condition: CreateBudget
    Type: AWS::Budgets::Budget
    Properties: 
      Budget: 
        BudgetLimit: 
          Amount: !Ref BillingAlertThreshold
          Unit: USD
        BudgetName: !Ref BudgetName
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers: 
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers: 
            - Address: !GetAtt SNSForAlert.Outputs.SNSTopicArn
              SubscriptionType: SNS
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers: 
            - Address: !GetAtt SNSForAlert.Outputs.SNSTopicArn
              SubscriptionType: SNS
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers: 
            - Address: !GetAtt SNSForAlert.Outputs.SNSTopicArn
              SubscriptionType: SNS
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 150
            ThresholdType: PERCENTAGE
          Subscribers: 
            - Address: !GetAtt SNSForAlert.Outputs.SNSTopicArn
              SubscriptionType: SNS
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 200
            ThresholdType: PERCENTAGE
          Subscribers: 
            - Address: !GetAtt SNSForAlert.Outputs.SNSTopicArn
              SubscriptionType: SNS
  # CertificateManager
  CertificateManager:
    Condition: CreateACMCertificate
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref ACMDomainName
      ValidationMethod: !Ref ACMValidationMethod
      DomainValidationOptions: !If
        - CreateRoute53
        - - DomainName: !Ref ACMDomainName
            HostedZoneId: !Ref HostedZone
        - !Ref AWS::NoValue
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CertificateManagerAccount:
    Condition: CreateACMCertificate
    Type: AWS::CertificateManager::Account
    Properties:
      ExpiryEventsConfiguration: 
        DaysBeforeExpiry: 45         
  # CloudWatch Alarm for ACM
  CloudWatchAlarmACM:
    Condition: CreateACMCertificate
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-acm
        SemanticVersion: 2.2.14
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        CustomAlarmName: !Ref AWS::StackName
        SNSTopicArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        CertificateArn: !Ref CertificateManager
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue 
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # Route53
  HostedZone:
    Condition: CreateRoute53
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: !Ref DomainName
      HostedZoneTags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      Name: !Ref DomainName
  # CloudWatch
  CloudWatchAlarmBilling:
    Condition: CreateCloudWatchAlarmBilling
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      AlarmDescription: !Sub '*概算請求金額* が *$ ${BillingAlertThreshold} を超過* しています。'
      AlarmName: !Sub Warning-${AWS::StackName}-EstimatedCharges-is-Over-${BillingAlertThreshold}00-Yen
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      OKActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      Period: 21600
      Statistic: Maximum
      Threshold: !Ref BillingAlertThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchAlarmCloudFront4xxErrorRate:
    Condition: CreateCloudWatchAlarmCloudFrontErrorRate
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      AlarmDescription: '*CloudFront* の *4XXエラー率が増加* しています。'
      AlarmName: !Sub Warning-${AWS::StackName}-CloudFront-4XXErrorRate-Increased
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Region
          Value: Global
        - Name: DistributionId
          Value: !Ref CloudFrontDistributionId 
      EvaluationPeriods: 1
      MetricName: 4xxErrorRate
      Namespace: AWS/CloudFront
      OKActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      Period: 300
      Statistic: Average
      Threshold: !Ref CloudFrontErrorRateThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchAlarmCloudFront5xxErrorRate:
    Condition: CreateCloudWatchAlarmCloudFrontErrorRate
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      AlarmDescription: '*CloudFront* の *5XXエラー率が増加* しています。'
      AlarmName: !Sub Warning-${AWS::StackName}-CloudFront-5XXErrorRate-Increased
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Region
          Value: Global
        - Name: DistributionId
          Value: !Ref CloudFrontDistributionId 
      EvaluationPeriods: 1
      MetricName: 5xxErrorRate
      Namespace: AWS/CloudFront
      OKActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      Period: 300
      Statistic: Average
      Threshold: !Ref CloudFrontErrorRateThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchAlarmCloudFrontTotalErrorRate:
    Condition: CreateCloudWatchAlarmCloudFrontErrorRate
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      AlarmDescription: '*CloudFront* の *エラー率が増加* しています。'
      AlarmName: !Sub Warning-${AWS::StackName}-CloudFront-TotalErrorRate-Increased
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Region
          Value: Global
        - Name: DistributionId
          Value: !Ref CloudFrontDistributionId 
      EvaluationPeriods: 1
      MetricName: TotalErrorRate
      Namespace: AWS/CloudFront
      OKActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      Period: 300
      Statistic: Average
      Threshold: !Ref CloudFrontErrorRateThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchAlarmCloudFrontRequests:
    Condition: CreateCloudWatchAlarmCloudFrontRequests
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      AlarmDescription: '*CloudFront* の *リクエスト数が増加* しています。'
      AlarmName: !Sub Warning-${AWS::StackName}-CloudFront-Requests-Increased
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Region
          Value: Global
        - Name: DistributionId
          Value: !Ref CloudFrontDistributionId 
      EvaluationPeriods: 1
      MetricName: Requests
      Namespace: AWS/CloudFront
      OKActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: !Ref CloudFrontErrorRequestPerMinuteThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchAlarmCloudFrontBytesDownloaded:
    Condition: CreateCloudWatchAlarmCloudFrontBytesDownloaded
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      AlarmDescription: '*CloudFront* の *ダウンロードサイズが増加* しています。'
      AlarmName: !Sub Warning-${AWS::StackName}-CloudFront-BytesDownloaded-Increased
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Region
          Value: Global
        - Name: DistributionId
          Value: !Ref CloudFrontDistributionId 
      EvaluationPeriods: 1
      MetricName: BytesDownloaded
      Namespace: AWS/CloudFront
      OKActions:
        - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: !Ref CloudFrontBytesDownloadedPerMinuteThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
    
Outputs:
  CertificationARN:
    Condition: CreateACMCertificate
    Description: Certification ARN
    Value: !Ref CertificateManager
  HostedZoneId:
    Description: Hosted Zone Id
    Value: !If
      - CreateRoute53
      - !Ref HostedZone
      - ''
  WebACLArn:
    Description: WebACL Arn
    Value: !If
      - CreateWebACL
      - !GetAtt WAF.Outputs.WebACLArn
      - ''