AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/euc/workspaces sets Amazon Workspaces.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Microsoft Active Directory Configuration'
        Parameters:
          - ActiveDirectoryIdForWorkspaces
      - Label: 
          default: 'Workspaces Configuration'
        Parameters: 
          - WorkspacesDeploy
          - WorkspacesBundleId
          - WorkspacesComputeTypeName
          - WorkspacesRootVolumeSizeGib
          - WorkspacesRunningMode
          - WorkspacesWorkspacesRunningModeAutoStopTimeoutInMinutes
          - WorkspacesUserNames
          - WorkspacesUserVolumeSizeGib
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment 
          - TagKey
          - TagValue

Parameters:
  ActiveDirectoryIdForWorkspaces:
    Type: String
    Default: ''
    Description: The identifier of the AWS Directory Service directory for Workspaces [conditional]
  WorkspacesComputeTypeName:
    Type: String
    Default: PERFORMANCE
    Description: The compute type
  WorkspacesBundleId:
    Type: String
    Default: wsb-7jspy3qyc
    Description: The identifier of the bundle for the WorkSpace [required]
  WorkspacesDeploy:
    Type: String
    Default: WORKSPACES
    AllowedValues:
      - VPC_ONLY
      - WORKSPACES
    Description: The scope of the deploy. Amazon Workspaces can be built after you register a directory manually [required]
  WorkspacesRootVolumeSizeGib:
    Type: Number
    Default: 80
    Description: The size of the root volume [required]  
  WorkspacesRunningMode:
    Type: String
    Default: AUTO_STOP
    AllowedValues:
      - ALWAYS_ON
      - AUTO_STOP
      - MANUAL
    Description: The identifier of the bundle for the WorkSpace [required]
  WorkspacesWorkspacesRunningModeAutoStopTimeoutInMinutes:
    Type: Number
    Default: 60
    Description: The time after a user logs off when WorkSpaces are automatically stopped [required]
  WorkspacesUserNames:
    Type: CommaDelimitedList
    Default: unknown
    AllowedPattern: .+
    Description: The user name of the user for the WorkSpace [required]
  WorkspacesUserVolumeSizeGib:
    Type: Number
    Default: 100
    Description: The size of the user storage [required] 
  SNSForAlertArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for deployment information
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateWorkspaces: !Equals [ !Ref WorkspacesDeploy, WORKSPACES]

Resources:
  # Workspaces
  'Fn::ForEach::Workspaces':
    - UserName
    - !Ref WorkspacesUserNames
    - Workspaces${UserName}:
        Type: AWS::WorkSpaces::Workspace
        # Conditions must be the second property listed, or later. Stack creation will fail if Conditions is the first property listed within the template fragment parameter of Fn::ForEach.
        Condition: CreateWorkspaces
        Properties: 
          BundleId: !Ref WorkspacesBundleId
          DirectoryId: !Ref ActiveDirectoryIdForWorkspaces
          RootVolumeEncryptionEnabled: false
          Tags: 
            - Key: environment
              Value: !Ref Environment
            - Key: !Ref TagKey
              Value: !Ref TagValue
          UserName: !Ref UserName
          UserVolumeEncryptionEnabled: false
          WorkspaceProperties: 
            ComputeTypeName: !Ref WorkspacesComputeTypeName
            RootVolumeSizeGib: !Ref WorkspacesRootVolumeSizeGib
            RunningMode: !Ref WorkspacesRunningMode
            RunningModeAutoStopTimeoutInMinutes: !Ref WorkspacesWorkspacesRunningModeAutoStopTimeoutInMinutes
            UserVolumeSizeGib: !Ref WorkspacesUserVolumeSizeGib
  # CloudWatch
  CloudWatchAlarmWorkspaces:
    Condition: CreateWorkspaces
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-workspaces
        SemanticVersion: 2.2.13
      NotificationARNs: 
        - !Ref SNSForDeploymentArn
      Parameters:
        CustomAlarmName: !Ref AWS::StackName
        DirectoryId: !Ref ActiveDirectoryIdForWorkspaces
        SNSTopicArn: !Ref SNSForAlertArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue