AWSTemplateFormatVersion: 2010-09-09
Transform: 
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: aws-cloudformation-templates/identity/microsoftad sets AWS IAM Identity Center.
Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'Identity Center Configuration'
        Parameters:
          - DefaultSessionDuration 
          - InstanceArn
      - Label: 
          default: 'Account Assignment Configuration'
        Parameters:
          - AdministratorGroupId
          - ReadOnlyGroupId
          - AdministratorTargetAccountIds
          - ReadOnlyTargetAccountIds
          - ManagementAccountId
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalName
          - Environment
          - TagKey
          - TagValue
          
Parameters:
  DefaultSessionDuration:
    Type: String
    Default: PT12H
    MinLength: 1
    MaxLength: 100
    AllowedPattern: ^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$
    Description: The length of time that the application user sessions are valid for in the ISO-8601 standard [required]
  InstanceArn:
    Type: String
    Default: ''
    Description: The ARN of the IAM Identity Center instance under which the operation will be executed
  AdministratorGroupId:
    Type: String
    Default: ''
    Description: The identity store group id that receives administrator access
  ReadOnlyGroupId:
    Type: String
    Default: ''
    Description: The identity store group id that receives read only access
  AdministratorTargetAccountIds:
    Type: CommaDelimitedList
    Default: '000000000000'
    AllowedPattern: \d{12}
    Description: The account ids that administrator access is assigned to
  ReadOnlyTargetAccountIds:
    Type: CommaDelimitedList
    Default: '000000000000'
    AllowedPattern: \d{12}
    Description: The account ids that read only access is assigned to
  ManagementAccountId:
    Type: String
    Default: ''
    Description: The management account id that organizations and service catalog access is assigned to
  LogicalName:
    Type: String
    Default: IdentityCenter
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreatePermissionSet: !Not [ !Equals [ !Ref InstanceArn, ''] ]
  CreateAdministratorAssignment: !And [ !Not [ !Equals [ !Ref InstanceArn, ''] ], !Not [ !Equals [ !Ref AdministratorGroupId, ''] ], !Not [ !Equals [ !Join [ '', !Ref AdministratorTargetAccountIds ], '000000000000'] ] ]
  CreateReadOnlyAssignment: !And [ !Not [ !Equals [ !Ref InstanceArn, ''] ], !Not [ !Equals [ !Ref ReadOnlyGroupId, ''] ], !Not [ !Equals [ !Join [ '', !Ref ReadOnlyTargetAccountIds ], '000000000000'] ] ]
  CreateAssignmentForManagementAccount: !And [ !Not [ !Equals [ !Ref InstanceArn, ''] ], !Not [ !Equals [ !Ref AdministratorGroupId, ''] ], !Not [ !Equals [ !Ref ManagementAccountId, ''] ] ]
  CreateReadOnlyAssignmentForManagementAccount: !And [ !Not [ !Equals [ !Ref InstanceArn, ''] ], !Not [ !Equals [ !Ref ReadOnlyGroupId, ''] ], !Not [ !Equals [ !Ref ManagementAccountId, ''] ] ]

Resources:
  AdministratorAccess:
    Condition: CreatePermissionSet
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: !Sub Provides full access to AWS services and resources created by ${AWS::StackName}
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/AdministratorAccess
      Name: !Sub ${LogicalName}Administrator
      SessionDuration: !Ref DefaultSessionDuration
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  PowerUserAccess:
    Condition: CreatePermissionSet
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: !Sub Provides full access to AWS services and resources, but does not allow management of Users and groups created by ${AWS::StackName}
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/PowerUserAccess
      Name: !Sub ${LogicalName}PowerUser
      SessionDuration: !Ref DefaultSessionDuration
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue  
  OrganizationsFullAccess:
    Condition: CreatePermissionSet
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: !Sub Provides full access to AWS Organizations created by ${AWS::StackName}
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/AWSOrganizationsFullAccess
      Name: !Sub ${LogicalName}OrganizationsFull
      SessionDuration: !Ref DefaultSessionDuration
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  QuickWorkspacesAccess:
    Condition: CreatePermissionSet
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: !Sub Provides end user access to Amazon Quick and Amazon WorkSpaces only created by ${AWS::StackName}
      InlinePolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - quicksight:Describe*
              - quicksight:Get*
              - quicksight:List*
              - quicksight:Search*
            Resource: '*'
          - Effect: Allow
            Action:
              - workspaces:Describe*
            Resource: '*'
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/AmazonWorkSpacesSelfServiceAccess
      Name: !Sub ${LogicalName}QuickWorkspaces
      SessionDuration: !Ref DefaultSessionDuration
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CatalogAdminAccess:
    Condition: CreatePermissionSet
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: !Sub Provides full access to AWS Service Catalog administrator capabilities created by ${AWS::StackName}
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess
      Name: !Sub ${LogicalName}CatalogAdmin
      SessionDuration: !Ref DefaultSessionDuration
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CatalogEndUserAccess:
    Condition: CreatePermissionSet
    Type: AWS::SSO::PermissionSet
    Properties: 
      Description: !Sub Provides full access to AWS Service Catalog end user capabilities created by ${AWS::StackName}
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess
      Name: !Sub ${LogicalName}CatalogEndUser
      SessionDuration: !Ref DefaultSessionDuration
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # Account Assignments
  Fn::ForEach::AssignmentForAdministrator:
    - AccountId
    - !Ref AdministratorTargetAccountIds
    - AssignmentForAdministrator${AccountId}:
        Type: AWS::SSO::Assignment
        # Conditions must be the second property listed, or later. Stack creation will fail if Conditions is the first property listed within the template fragment parameter of Fn::ForEach.
        Condition: CreateAdministratorAssignment
        Properties: 
          InstanceArn: !Ref InstanceArn
          PermissionSetArn: !GetAtt AdministratorAccess.PermissionSetArn
          PrincipalId: !Ref AdministratorGroupId
          PrincipalType: GROUP
          TargetId: !Ref AccountId
          TargetType: AWS_ACCOUNT
  Fn::ForEach::AssignmentForReadOnly:
    - AccountId
    - !Ref ReadOnlyTargetAccountIds
    - AssignmentForReadOnly${AccountId}:
        Type: AWS::SSO::Assignment
        Condition: CreateReadOnlyAssignment
        Properties: 
          InstanceArn: !Ref InstanceArn
          PermissionSetArn: !GetAtt QuickWorkspacesAccess.PermissionSetArn
          PrincipalId: !Ref ReadOnlyGroupId
          PrincipalType: GROUP
          TargetId: !Ref AccountId
          TargetType: AWS_ACCOUNT
  AssignmentForOrganizationsFull:
    Condition: CreateAssignmentForManagementAccount
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref InstanceArn
      PermissionSetArn: !GetAtt OrganizationsFullAccess.PermissionSetArn
      PrincipalId: !Ref AdministratorGroupId
      PrincipalType: GROUP
      TargetId: !Ref ManagementAccountId
      TargetType: AWS_ACCOUNT
  AssignmentForCatalogAdmin:
    Condition: CreateAssignmentForManagementAccount
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref InstanceArn
      PermissionSetArn: !GetAtt CatalogAdminAccess.PermissionSetArn
      PrincipalId: !Ref AdministratorGroupId
      PrincipalType: GROUP
      TargetId: !Ref ManagementAccountId
      TargetType: AWS_ACCOUNT
  AssignmentForCatalogEndUser:
    Condition: CreateReadOnlyAssignmentForManagementAccount
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref InstanceArn
      PermissionSetArn: !GetAtt CatalogEndUserAccess.PermissionSetArn
      PrincipalId: !Ref ReadOnlyGroupId
      PrincipalType: GROUP
      TargetId: !Ref ManagementAccountId
      TargetType: AWS_ACCOUNT