AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/identity/microsoftad sets AWS Directory Service for Microsoft Active Directory.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Microsoft Active Directory Configuration'
        Parameters: 
          - Edition
          - EnableSso
          - Name
          - ShortName
          - Password
          - VPCId
          - SubnetPrivateCidrBlockForAz1
          - SubnetPrivateIdForAz1
          - SubnetPrivateCidrBlockForAz2
          - SubnetPrivateIdForAz2
          - SubnetPrivateCidrBlockForAz3
          - SubnetPrivateIdForAz3
      - Label: 
          default: 'Management Instance Configuration'
        Parameters: 
          - EC2ImageId
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - AlarmLevel
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalName
          - Environment 
          - TagKey
          - TagValue

Parameters:
  AlarmLevel:
    Type: String
    Default: NOTICE
    AllowedValues:
      - NOTICE
      - WARNING
    Description: The alarm level of CloudWatch alarms
  EC2ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2022-Japanese-Full-Base
    Description: The EC2 Image Id [required]
  Edition:
    Type: String
    Default: Standard
    AllowedValues:
      - Enterprise
      - Standard
    Description: The edition of AWS Directory Service for Microsoft Active Directory [required]
  EnableSso:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether to enable single sign-on for a Microsoft Active Directory in AWS [required]
  Name:
    Type: String
    Default: corp.example.com
    AllowedPattern: ^([a-zA-Z0-9]+[\\.-])+([a-zA-Z0-9])+$
    Description: The fully qualified domain name for the AWS Managed Microsoft AD directory [required]
  Password:
    Type: String
    Default: Password1+
    AllowedPattern: (?=^.{8,64}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9\s])(?=.*[a-z])|(?=.*[^A-Za-z0-9\s])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9\s]))^.*
    NoEcho: true
    Description: The password for the default administrative user named Admin [required]
  ShortName:
    Type: String
    Default: CORP
    AllowedPattern: ^[^\\/:*?"<>|.]+[^\\/:*?"<>|]*$
    Description: The NetBIOS name for your domain [required]
  SubnetPrivateCidrBlockForAz1:
    Type: String
    Default: 10.3.0.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block at AZ1 [conditional]
  SubnetPrivateIdForAz1:
    Type: String
    Default: ''
    Description: The private subnet id at AZ1 [conditional]
  SubnetPrivateCidrBlockForAz2:
    Type: String
    Default: 10.3.4.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block at AZ2 [conditional]
  SubnetPrivateIdForAz2:
    Type: String
    Default: ''
    Description: The private subnet id at AZ2 [conditional]
  SubnetPrivateCidrBlockForAz3:
    Type: String
    Default: 10.3.8.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block at AZ3 [conditional]
  SubnetPrivateIdForAz3:
    Type: String
    Default: ''
    Description: The private subnet id at AZ3 [conditional]
  VPCId:
    Type: AWS::EC2::VPC::Id
    AllowedPattern: .+
    Description: The VPC id [required]
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for deployment information
  LogicalName:
    Type: String
    Default: MicrosoftAD
    AllowedPattern: .+
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateAz1: !Equals [ !Ref SubnetPrivateIdForAz1, '']
  CreateAz2: !Equals [ !Ref SubnetPrivateIdForAz2, '']
  CreateAz3: !Equals [ !Ref SubnetPrivateIdForAz3, '']
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']
  Development: !Equals [ !Ref Environment, development]

Resources:
  # Nested Stack
  Az1:
    Condition: CreateAz1
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/availability-zone
        SemanticVersion: 2.2.9
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        AvailabilityZone: !Select 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
        LogicalName: !Ref AWS::StackName
        SubnetPrivateCidrBlock: !Ref SubnetPrivateCidrBlockForAz1
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn   
        VPCId: !Ref VPCId
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  Az2:
    Condition: CreateAz2
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/availability-zone
        SemanticVersion: 2.2.9
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        AvailabilityZone: !Select
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
        LogicalName: !Ref AWS::StackName
        SubnetPrivateCidrBlock: !Ref SubnetPrivateCidrBlockForAz2
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn 
        VPCId: !Ref VPCId
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue 
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  Az3:
    Condition: CreateAz3
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/availability-zone
        SemanticVersion: 2.2.9
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        AvailabilityZone: !Select
          - 2
          - Fn::GetAZs: !Ref 'AWS::Region'
        LogicalName: !Ref AWS::StackName
        SubnetPrivateCidrBlock: !Ref SubnetPrivateCidrBlockForAz3
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn 
        VPCId: !Ref VPCId
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue 
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.9
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.9
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # IAM
  IAMRoleForManagementInstance:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Description: A role required for Managed Instances.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        # for Microsoft AD
        - arn:aws:iam::aws:policy/AmazonSSMDirectoryServiceAccess
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::aws-ssm-${AWS::Region}/*'
                  - !Sub 'arn:aws:s3:::aws-windows-downloads-${AWS::Region}/*'
                  - !Sub 'arn:aws:s3:::amazon-ssm-${AWS::Region}/*'
                  - !Sub 'arn:aws:s3:::amazon-ssm-packages-${AWS::Region}/*'
                  - !Sub 'arn:aws:s3:::${AWS::Region}-birdwatcher-prod/*'
                  - !Sub 'arn:aws:s3:::aws-ssm-distributor-file-${AWS::Region}/*'
                  - !Sub 'arn:aws:s3:::aws-ssm-document-attachments-${AWS::Region}/*'
                  - !Sub 'arn:aws:s3:::patch-baseline-snapshot-${AWS::Region}/*'
      RoleName: !Sub '${LogicalName}-AWSEC2Role-${AWS::Region}'
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  IamInstanceProfileForIAMRoleForManagementInstance:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Ref IAMRoleForManagementInstance
      Roles: 
        - !Ref IAMRoleForManagementInstance
  # Active Directory
  ActiveDirectory:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
      CreateAlias: true
      Edition: !Ref Edition
      EnableSso: !Ref EnableSso
      Name: !Ref Name
      Password: !Ref Password
      ShortName: !Ref ShortName
      VpcSettings: 
          SubnetIds:
            - !If 
              - CreateAz1
              - !GetAtt Az1.Outputs.PrivateSubnetId
              - !Ref SubnetPrivateIdForAz1
            - !If 
              - CreateAz2
              - !GetAtt Az2.Outputs.PrivateSubnetId
              - !Ref SubnetPrivateIdForAz2
          VpcId: !Ref VPCId
  DHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties: 
      DomainName: !Ref Name
      DomainNameServers: 
        - AmazonProvidedDNS
      Tags: 
        - Key: Name
          Value: !Sub dopt-${AWS::StackName}-${AWS::Region}
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  DHCPOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties: 
      DhcpOptionsId: !GetAtt DHCPOptions.DhcpOptionsId
      VpcId: !Ref VPCId
  # EC2
  ManagementInstance:
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            '01-install-packages':
              command: 'powershell.exe -Command "Install-WindowsFeature -Name GPMC,RSAT-AD-PowerShell,RSAT-AD-AdminCenter,RSAT-ADDS-Tools,RSAT-DNS-Server"'
              waitAfterCompletion: '0'
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: /dev/sda1
          Ebs: 
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: 30
            VolumeType: gp3
      EbsOptimized: true
      ImageId: !Ref EC2ImageId
      IamInstanceProfile: !Ref IamInstanceProfileForIAMRoleForManagementInstance
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t3.micro
      KeyName: !Ref EC2KeyPair
      Monitoring: true
      SecurityGroupIds: 
        - !Ref SecurityGroupForManagementInstance
      SsmAssociations: 
        - AssociationParameters: 
            - Key: directoryId
              Value:
               - !Ref ActiveDirectory
            - Key: directoryName
              Value:
               - !Ref Name
            - Key: dnsIpAddresses
              Value: !GetAtt ActiveDirectory.DnsIpAddresses       
          DocumentName: AWS-JoinDirectoryServiceDomain
      SubnetId: !If 
        - CreateAz1
        - !GetAtt Az1.Outputs.PrivateSubnetId
        - !Ref SubnetPrivateIdForAz1
      UserData: !Base64
        Fn::Join:
          - ''
          - - "<script>\n"
            - 'cfn-init.exe --configsets config -v --stack '
            - !Ref 'AWS::StackName'
            - ' --resource ManagementInstance'
            - ' --region '
            - !Ref 'AWS::Region'
            - "\n"
            - "</script>\n"
      Tags: 
        - Key: Name
          Value: !Sub ec2-${AWS::StackName}-${AWS::Region}
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # The key is stored in AWS Systems Manager Parameter Store
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub ec2-${AWS::StackName}-${AWS::Region}
  SecurityGroupForManagementInstance:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # CloudFormation cannot update a stack when a custom-named resource requires replacing.
      GroupName: !Sub sgp-${AWS::StackName}-${AWS::Region}-mgmt-20221129
      GroupDescription: Security Group for a management instance
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
      Tags:
        - Key: Name
          Value: !Sub sgp-${AWS::StackName}-${AWS::Region}-mgmt
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VpcId: !Ref VPCId
  # Data Lifecycle Manager
  DataLifecycleManager:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        DailySnapshotScheduledAt: '17:00'
        LogicalName: !Ref LogicalName
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue 
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/web-servers/dlm.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/web-servers/dlm.yaml
  # CloudWatch
  CloudWatchAlarmDirectoryServiceAz1:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-directoryservice
        SemanticVersion: 2.2.9
      NotificationARNs: 
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters: 
        AlarmLevel: !Ref AlarmLevel
        CustomAlarmName : !Sub ${AWS::StackName}-0
        DirectoryId: !Ref ActiveDirectory
        DomainControllerIp: !Select [ 0, !GetAtt ActiveDirectory.DnsIpAddresses ]
        SNSTopicArn: !If 
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  CloudWatchAlarmDirectoryServiceAz2:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-directoryservice
        SemanticVersion: 2.2.9
      NotificationARNs: 
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters: 
        CustomAlarmName : !Sub ${AWS::StackName}-1
        DirectoryId: !Ref ActiveDirectory
        DomainControllerIp: !Select [ 1, !GetAtt ActiveDirectory.DnsIpAddresses ]
        SNSTopicArn: !If 
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

Outputs:
  MicrosoftAdDnsIpAddresses:
    Description: The IP addresses of the DNS servers for Active Directory
    Value: !Join
      - ','
      - !GetAtt ActiveDirectory.DnsIpAddresses
  MicrosoftAdId:
    Description: The Id of the Active Directory
    Value: !Ref ActiveDirectory
  RouteTableIdPrivateAz1:
    Description: The route table for private subnet
    Value: !If 
      - CreateAz1
      - !GetAtt Az1.Outputs.RouteTableIdPrivate
      - ''
  RouteTableIdPrivateAz2:
    Description: The route table for private subnet
    Value: !If 
      - CreateAz2
      - !GetAtt Az2.Outputs.RouteTableIdPrivate
      - ''
  PrivateSubnetId1:
    Description: The ID of the private subnet
    Value: !If
      - CreateAz1
      - !GetAtt Az1.Outputs.PrivateSubnetId
      - !Ref SubnetPrivateIdForAz1
  PrivateSubnetId2:
    Description: The ID of the private subnet
    Value: !If
      - CreateAz2
      - !GetAtt Az2.Outputs.PrivateSubnetId
      - !Ref SubnetPrivateIdForAz2
  PrivateSubnetId3:
    Description: The ID of the private subnet
    Value: !If
      - CreateAz3
      - !GetAtt Az3.Outputs.PrivateSubnetId
      - !Ref SubnetPrivateIdForAz3
  WindowsServerKeyPair:
    Description: The key pair for Windows Server
    Value: The key is stored in AWS Systems Manager Parameter Store