AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/media/mediaconvert sets Elemental MediaConvert.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'MediaConvert Configuration'
        Parameters: 
          - AccelerationSettings
          - Category
          - Name
          - StatusUpdateInterval
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters: 
          - LogicalName
          - Environment
          - TagKey
          - TagValue

Parameters:
  AccelerationSettings:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - PREFERRED
      - DISABLED
    Description: Specify the conditions when the service will run your job with accelerated transcoding [required]
  Category:
    Type: String
    Default: Default
    Description: A category for the job template you are creating [required]
  Name:
    Type: String
    Default: Default
    Description: The name of the job template you are creating [required]
  StatusUpdateInterval:
    Type: Number
    Default: 60
    AllowedValues:
      - 10
      - 12
      - 15
      - 20
      - 30
      - 60
      - 120
      - 180
      - 240
      - 300
      - 360
      - 420
      - 480
      - 540
      - 600
    Description: How often MediaConvert sends STATUS_UPDATE events to Amazon CloudWatch Events [required]
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for deployment information
  LogicalName:
    Type: String
    Default: MediaConvert
    AllowedPattern: .+
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates 
    AllowedPattern: .+

Conditions:
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']

Resources:
  # Nested Stack
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.10
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.10
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # IAM Role
  IAMRoleForMediaConvert:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com 
            Action: sts:AssumeRole
      Description: A role required for MediaConvert to access S3.
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: !Sub ${LogicalName}-MediaConvert-${AWS::Region}
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  MediaConvertJobTemplate:
    Type: AWS::MediaConvert::JobTemplate
    Properties: 
      AccelerationSettings: 
        Mode: !Ref AccelerationSettings
      Category: !Ref Category
      Description: !Ref Name
      Name: !Ref Name
      Priority: 0
      Queue: Default
      SettingsJson: 
        OutputGroups: 
          - Name: "Apple HLS"
            Outputs: 
              - ContainerSettings: 
                  Container: M3U8
                  M3u8Settings: 
                    AudioFramesPerPes: 4
                    PcrControl: PCR_EVERY_PES_PACKET
                    PmtPid: 480
                    PrivateMetadataPid: 503
                    ProgramNumber: 1
                    PatInterval: 0
                    PmtInterval: 0
                    Scte35Source: NONE
                    NielsenId3: NONE
                    TimedMetadata: NONE
                    VideoPid: 481
                    AudioPids: 
                    - 482
                    - 483
                    - 484
                    - 485
                    - 486
                    - 487
                    - 488
                    - 489
                    - 490
                    - 491
                    - 492
                VideoDescription: 
                  Width: 1280
                  ScalingBehavior: DEFAULT
                  Height: 720
                  TimecodeInsertion: DISABLED
                  AntiAlias: ENABLED
                  Sharpness: 50
                  CodecSettings: 
                    Codec: H_264
                    H264Settings: 
                      InterlaceMode: PROGRESSIVE
                      NumberReferenceFrames: 3
                      Syntax: DEFAULT
                      Softness: 0
                      GopClosedCadence: 1
                      GopSize: 60
                      Slices: 1
                      GopBReference: DISABLED
                      SlowPal: DISABLED
                      SpatialAdaptiveQuantization: ENABLED
                      TemporalAdaptiveQuantization: ENABLED
                      FlickerAdaptiveQuantization: DISABLED
                      EntropyEncoding: CABAC
                      Bitrate: 15000000
                      FramerateControl: INITIALIZE_FROM_SOURCE
                      RateControlMode: CBR
                      CodecProfile: MAIN
                      Telecine: NONE
                      MinIInterval: 0
                      AdaptiveQuantization: HIGH
                      CodecLevel: AUTO
                      FieldEncoding: PAFF
                      SceneChangeDetect: ENABLED
                      QualityTuningLevel: SINGLE_PASS
                      FramerateConversionAlgorithm: DUPLICATE_DROP
                      UnregisteredSeiTimecode: DISABLED
                      GopSizeUnits: FRAMES
                      ParControl: INITIALIZE_FROM_SOURCE
                      NumberBFramesBetweenReferenceFrames: 2
                      RepeatPps: DISABLED
                      DynamicSubGop: STATIC
                  AfdSignaling: NONE
                  DropFrameTimecode: ENABLED
                  RespondToAfd: NONE
                  ColorMetadata: INSERT
                AudioDescriptions: 
                  - AudioTypeControl: FOLLOW_INPUT
                    CodecSettings: 
                      Codec: AAC
                      AacSettings: 
                        AudioDescriptionBroadcasterMix: NORMAL
                        Bitrate: 96000
                        RateControlMode: CBR
                        CodecProfile: LC
                        CodingMode: CODING_MODE_2_0
                        RawFormat: NONE
                        SampleRate: 48000
                        Specification: MPEG4
                    LanguageCodeControl: FOLLOW_INPUT
                OutputSettings: 
                  HlsSettings: 
                    AudioGroupId: program_audio
                    AudioOnlyContainer: AUTOMATIC
                    IFrameOnlyManifest: EXCLUDE
                NameModifier: s1
              - ContainerSettings: 
                  Container: M3U8
                  M3u8Settings: 
                    AudioFramesPerPes: 4
                    PcrControl: PCR_EVERY_PES_PACKET
                    PmtPid: 480
                    PrivateMetadataPid: 503
                    ProgramNumber: 1
                    PatInterval: 0
                    PmtInterval: 0
                    Scte35Source: NONE
                    NielsenId3: NONE
                    TimedMetadata: NONE
                    TimedMetadataPid: 502
                    VideoPid: 481
                    AudioPids: 
                    - 482
                    - 483
                    - 484
                    - 485
                    - 486
                    - 487
                    - 488
                    - 489
                    - 490
                    - 491
                    - 492
                VideoDescription: 
                  Width: 640
                  ScalingBehavior: DEFAULT
                  Height: 360
                  TimecodeInsertion: DISABLED
                  AntiAlias: ENABLED
                  Sharpness: 50
                  CodecSettings: 
                    Codec: H_264
                    H264Settings: 
                      InterlaceMode: PROGRESSIVE
                      NumberReferenceFrames: 3
                      Syntax: DEFAULT
                      Softness: 0
                      GopClosedCadence: 1
                      GopSize: 60
                      Slices: 1
                      GopBReference: DISABLED
                      SlowPal: DISABLED
                      SpatialAdaptiveQuantization: ENABLED
                      TemporalAdaptiveQuantization: ENABLED
                      FlickerAdaptiveQuantization: DISABLED
                      EntropyEncoding: CABAC
                      Bitrate: 1000000
                      FramerateControl: INITIALIZE_FROM_SOURCE
                      RateControlMode: CBR
                      CodecProfile: MAIN
                      Telecine: NONE
                      MinIInterval: 0
                      AdaptiveQuantization: HIGH
                      CodecLevel: AUTO
                      FieldEncoding: PAFF
                      SceneChangeDetect: ENABLED
                      QualityTuningLevel: SINGLE_PASS
                      FramerateConversionAlgorithm: DUPLICATE_DROP
                      UnregisteredSeiTimecode: DISABLED
                      GopSizeUnits: FRAMES
                      ParControl: INITIALIZE_FROM_SOURCE
                      NumberBFramesBetweenReferenceFrames: 2
                      RepeatPps: DISABLED
                      DynamicSubGop: STATIC
                  AfdSignaling: NONE
                  DropFrameTimecode: ENABLED
                  RespondToAfd: NONE
                  ColorMetadata: INSERT
                AudioDescriptions: 
                  - AudioTypeControl: FOLLOW_INPUT
                    CodecSettings: 
                      Codec: AAC
                      AacSettings: 
                        AudioDescriptionBroadcasterMix: NORMAL
                        Bitrate: 96000
                        RateControlMode: CBR
                        CodecProfile: LC
                        CodingMode: CODING_MODE_2_0
                        RawFormat: NONE
                        SampleRate: 48000
                        Specification: MPEG4
                    LanguageCodeControl: FOLLOW_INPUT
                OutputSettings: 
                  HlsSettings: 
                    AudioGroupId: program_audio
                    AudioOnlyContainer: AUTOMATIC
                    IFrameOnlyManifest: EXCLUDE
                NameModifier: s2
              - ContainerSettings: 
                  Container: M3U8
                  M3u8Settings: 
                    AudioFramesPerPes: 4
                    PcrControl: PCR_EVERY_PES_PACKET
                    PmtPid: 480
                    PrivateMetadataPid: 503
                    ProgramNumber: 1
                    PatInterval: 0
                    PmtInterval: 0
                    Scte35Source: NONE
                    NielsenId3: NONE
                    TimedMetadata: NONE
                    TimedMetadataPid: 502
                    VideoPid: 481
                    AudioPids: 
                    - 482
                    - 483
                    - 484
                    - 485
                    - 486
                    - 487
                    - 488
                    - 489
                    - 490
                    - 491
                    - 492
                VideoDescription: 
                  Width: 480
                  ScalingBehavior: DEFAULT
                  Height: 270
                  TimecodeInsertion: DISABLED
                  AntiAlias: ENABLED
                  Sharpness: 50
                  CodecSettings: 
                    Codec: H_264
                    H264Settings: 
                      InterlaceMode: PROGRESSIVE
                      NumberReferenceFrames: 3
                      Syntax: DEFAULT
                      Softness: 0
                      GopClosedCadence: 1
                      GopSize: 60
                      Slices: 1
                      GopBReference: DISABLED
                      SlowPal: DISABLED
                      SpatialAdaptiveQuantization: ENABLED
                      TemporalAdaptiveQuantization: ENABLED
                      FlickerAdaptiveQuantization: DISABLED
                      EntropyEncoding: CABAC
                      Bitrate: 800000
                      FramerateControl: INITIALIZE_FROM_SOURCE
                      RateControlMode: CBR
                      CodecProfile: MAIN
                      Telecine: NONE
                      MinIInterval: 0
                      AdaptiveQuantization: HIGH
                      CodecLevel: AUTO
                      FieldEncoding: PAFF
                      SceneChangeDetect: ENABLED
                      QualityTuningLevel: SINGLE_PASS
                      FramerateConversionAlgorithm: DUPLICATE_DROP
                      UnregisteredSeiTimecode: DISABLED
                      GopSizeUnits: FRAMES
                      ParControl: INITIALIZE_FROM_SOURCE
                      NumberBFramesBetweenReferenceFrames: 2
                      RepeatPps: DISABLED
                      DynamicSubGop: STATIC
                  AfdSignaling: NONE
                  DropFrameTimecode: ENABLED
                  RespondToAfd: NONE
                  ColorMetadata: INSERT
                AudioDescriptions: 
                  - AudioTypeControl: FOLLOW_INPUT
                    CodecSettings: 
                      Codec: AAC
                      AacSettings: 
                        AudioDescriptionBroadcasterMix: NORMAL
                        Bitrate: 96000
                        RateControlMode: CBR
                        CodecProfile: LC
                        CodingMode: CODING_MODE_2_0
                        RawFormat: NONE
                        SampleRate: 48000
                        Specification: MPEG4
                    LanguageCodeControl: FOLLOW_INPUT
                OutputSettings: 
                  HlsSettings: 
                    AudioGroupId: program_audio
                    AudioOnlyContainer: AUTOMATIC
                    IFrameOnlyManifest: EXCLUDE
                NameModifier: s3
            OutputGroupSettings: 
              Type: HLS_GROUP_SETTINGS
              HlsGroupSettings: 
                ManifestDurationFormat: INTEGER
                SegmentLength: 10
                TimedMetadataId3Period: 10
                CaptionLanguageSetting: OMIT
                TimedMetadataId3Frame: PRIV
                CodecSpecification: RFC_4281
                OutputSelection: MANIFESTS_AND_SEGMENTS
                ProgramDateTimePeriod: 600
                MinSegmentLength: 0
                MinFinalSegmentLength: 0
                DirectoryStructure: SINGLE_DIRECTORY
                ProgramDateTime: EXCLUDE
                SegmentControl: SEGMENTED_FILES
                ManifestCompression: NONE
                ClientCache: ENABLED
                StreamInfResolution: INCLUDE
        AdAvailOffset: 0
        Inputs: 
          - AudioSelectors: 
              Audio Selector 1: 
                Offset: 0
                DefaultSelection: DEFAULT
                ProgramSelection: 1
            VideoSelector: 
              ColorSpace: FOLLOW
              Rotate: DEGREE_0
            FilterEnable: AUTO
            PsiControl: USE_PSI
            FilterStrength: 0
            DeblockFilter: DISABLED
            DenoiseFilter: DISABLED
            TimecodeSource: EMBEDDED
      StatusUpdateInterval: !Sub SECONDS_${StatusUpdateInterval}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # CloudWatch
  CloudWatchAlarmMediaConvert:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-mediaconvert
        SemanticVersion: 2.2.10
      NotificationARNs: 
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        CustomAlarmName: !Ref AWS::StackName
        SNSTopicArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue