AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: aws-cloudformation-templates/analytics/google-analytics creates Google Analytics data processing resources.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Google Analytics Configuration"
        Parameters:
          - PropertyId
          - AccountId
          - ClientSecret
      - Label:
          default: "Glue Configuration"
        Parameters:
          - GlueJobTimeout
          - GlueWorkerCount
      - Label:
          default: "Tag Configuration"
        Parameters:
          - LogicalName
          - Environment
          - TagKey
          - TagValue
      - Label:
          default: "Git Integration Configuration"
        Parameters:
          - GitRepository
          - GitOwner
          - GitBranch
          - GitFolder
          - GitToken
      - Label:
          default: "Schedule Configuration"
        Parameters:
          - ScheduleEnabled
      - Label:
          default: "Parent Stack Resources"
        Parameters:
          - RawDataBucketName
          - IcebergDataBucketName
          - ScriptsBucketName
          - QueryResultsBucketName
          - AlertTopicArn
          - GlueDatabaseName

Parameters:
  AccountId:
    Type: String
    Default: ""
    Description: Google Analytics 4 Account ID
  AlertTopicArn:
    Type: String
    Description: ARN of the SNS topic for alerts
  ClientSecret:
    Type: String
    NoEcho: true
    AllowedPattern: .+
    Description: The Google Analytics 4 OAuth2 Client Secret [required]
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - production
      - test
      - development
    Description: The deployment environment
  GlueDatabaseName:
    Type: String
    Description: Name of the Glue Data Catalog database
  GlueJobTimeout:
    Type: Number
    Default: 60
    MinValue: 1
    MaxValue: 2880
    Description: Glue Job timeout in minutes
  GlueWorkerCount:
    Type: Number
    Default: 5
    MinValue: 2
    MaxValue: 100
    Description: Number of Glue workers
  IcebergDataBucketName:
    Type: String
    Description: Name of the S3 bucket for Iceberg data storage
  LogicalName:
    Type: String
    Description: Logical name for resource naming and cross-stack references [required]
    MinLength: 1
  PropertyId:
    Type: String
    AllowedPattern: .+
    Description: The Google Analytics 4 Property ID (also used as Client ID) [required]
  QueryResultsBucketName:
    Type: String
    Description: Name of the S3 bucket for Athena query results
  RawDataBucketName:
    Type: String
    Description: Name of the S3 bucket for raw data staging
  ScriptsBucketName:
    Type: String
    Description: Name of the S3 bucket for Glue scripts storage
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
    Description: The tag key for resource tagging
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+
    Description: The tag value for resource tagging
  GitRepository:
    Type: String
    Default: ""
    Description: Git repository URL for Visual ETL job source control (optional)
  GitOwner:
    Type: String
    Default: ""
    Description: Git repository owner/organization name (optional)
  GitBranch:
    Type: String
    Default: main
    Description: Git branch for Visual ETL job source control
  GitFolder:
    Type: String
    Default: glue-jobs
    Description: Folder path in Git repository for Visual ETL job storage
  GitToken:
    Type: String
    NoEcho: true
    Default: ""
    Description: GitHub/GitLab personal access token for authentication (optional)
  ScheduleEnabled:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable scheduled execution of the Glue job at 4:00 AM JST (UTC+9) daily

Resources:
  # IAM Roles
  IAMRoleForGlue:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Description: !Sub IAM role for AWS Glue jobs in ${AWS::StackName}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${RawDataBucketName}/*"
                  - !Sub "arn:aws:s3:::${IcebergDataBucketName}/*"
                  - !Sub "arn:aws:s3:::${ScriptsBucketName}/*"
                  - !Sub "arn:aws:s3:::${RawDataBucketName}"
                  - !Sub "arn:aws:s3:::${IcebergDataBucketName}"
                  - !Sub "arn:aws:s3:::${ScriptsBucketName}"
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:PutSecretValue
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${LogicalName}/*
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                Resource:
                  - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*
        - PolicyName: NetworkInterfaceAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterface
                  - ec2:DeleteNetworkInterface
                Resource: "*"
        - PolicyName: GlueDataCatalogAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:CreateDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:DeleteTable
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:CreatePartition
                  - glue:UpdatePartition
                  - glue:DeletePartition
                  - glue:BatchCreatePartition
                  - glue:BatchDeletePartition
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${LogicalName}*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${LogicalName}*/*
        - PolicyName: CloudWatchLogsAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/*
      RoleName: !Sub ${LogicalName}-google-analytics-glue-${AWS::Region}
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  IAMRoleForVisualETLLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Description: !Sub IAM role for Visual ETL Lambda function in ${AWS::StackName}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: GlueJobManagementPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:CreateJob
                  - glue:UpdateJob
                  - glue:DeleteJob
                  - glue:GetJob
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${LogicalName}-ga4-to-s3-ingestion-job
              - Effect: Allow
                Action:
                  - glue:TagResource
                  - glue:UntagResource
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${LogicalName}-ga4-to-s3-ingestion-job
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt IAMRoleForGlue.Arn
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${RawDataBucketName}/*"
                  - !Sub "arn:aws:s3:::${ScriptsBucketName}/*"
                  - !Sub "arn:aws:s3:::${RawDataBucketName}"
                  - !Sub "arn:aws:s3:::${ScriptsBucketName}"
      RoleName: !Sub ${LogicalName}-visual-etl-lambda-${AWS::Region}
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  # Other Resources (alphabetically ordered)

  CloudWatchAlarmLambda:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-lambda
        SemanticVersion: 2.2.14
      Parameters:
        CustomAlarmName: !Ref LogicalName
        FunctionResouceName: !Ref VisualETLLambdaFunction
        SNSTopicArn: !Ref AlertTopicArn
        TimeoutMilliseconds: 810000
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

  CloudWatchAlarmEstimatedCharges:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${LogicalName}-estimated-charges
      AlarmDescription: Alarm when estimated charges exceed threshold
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      AlarmActions:
        - !Ref AlertTopicArn
      TreatMissingData: notBreaching
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  CloudWatchAlarmGlue:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-glue
        SemanticVersion: 2.2.14
      Parameters:
        AlarmLevel: WARNING
        CustomAlarmName: !Ref LogicalName
        JobName: !Sub ${LogicalName}-ga4-to-s3-ingestion-job
        SNSTopicArn: !Ref AlertTopicArn
        TimeoutMilliseconds: 3300000
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

  GlueTableGA4CoreReports:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDatabaseName
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: ga4_core_reports
        StorageDescriptor:
          Columns:
            - Name: date
              Type: date
            - Name: activeusers
              Type: string
          Location: !Sub "s3://${IcebergDataBucketName}/ga4_core_reports/"
          InputFormat: org.apache.iceberg.mr.hive.HiveIcebergInputFormat
          OutputFormat: org.apache.iceberg.mr.hive.HiveIcebergOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.iceberg.mr.hive.HiveIcebergSerDe
        TableType: EXTERNAL_TABLE
      OpenTableFormatInput:
        IcebergInput:
          MetadataOperation: CREATE
          Version: "2"

  GlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        AuthenticationConfiguration:
          AuthenticationType: OAUTH2
          OAuth2Properties:
            OAuth2ClientApplication:
              UserManagedClientApplicationClientId: !Ref PropertyId
            OAuth2GrantType: AUTHORIZATION_CODE
            TokenUrl: "https://oauth2.googleapis.com/token"
          SecretArn: !Ref SecretsManager
        ConnectionProperties:
          ROLE_ARN: !GetAtt IAMRoleForGlue.Arn
        ConnectionType: GOOGLEANALYTICS4
        Description: !Sub Connection to Google Analytics 4 created by ${AWS::StackName}
        Name: !Sub Googleanalytics4 connection (${LogicalName})
        ValidateCredentials: false

  SecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Google Analytics 4 API authentication credentials
      Name: !Sub ${LogicalName}/google-analytics/${Environment}-v2
      SecretString: !Sub '{"USER_MANAGED_CLIENT_APPLICATION_CLIENT_SECRET":"${ClientSecret}"}'
      Tags:
        - Key: Name
          Value: !Sub ${LogicalName}-google-analytics-secret-${AWS::Region}
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  VisualETLJobForGA4Ingestion:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt VisualETLLambdaFunction.Arn
      JobName: !Sub ${LogicalName}-ga4-to-s3-ingestion-job
      ConnectionName: !Ref GlueConnection
      IcebergDataBucket: !Ref IcebergDataBucketName
      DatabaseName: !Ref GlueDatabaseName
      ScriptsBucket: !Ref ScriptsBucketName
      LogicalName: !Ref LogicalName
      IAMRoleArn: !GetAtt IAMRoleForGlue.Arn
      AccountId: !Ref AccountId
      # Git Integration Settings
      GitRepository: !Ref GitRepository
      GitOwner: !Ref GitOwner
      GitBranch: !Ref GitBranch
      GitFolder: !Ref GitFolder
      GitToken: !Ref GitToken

  VisualETLLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${LogicalName}-visual-etl-handler
      Description: Lambda function to manage Glue Visual ETL Jobs via CloudFormation custom resources
      CodeUri: ../src/lambda-functions/visual-etl-handler/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 900
      MemorySize: 256
      Role: !GetAtt IAMRoleForVisualETLLambda.Arn
      Environment:
        Variables:
          LOG_LEVEL: INFO
      Tracing: Active
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

  VisualETLLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LogicalName}-visual-etl-handler
      RetentionInDays: 14
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  GlueJobScheduleTrigger:
    Type: AWS::Glue::Trigger
    Condition: IsScheduleEnabled
    Properties:
      Name: !Sub ${LogicalName}-ga4-to-s3-ingestion-schedule
      Type: SCHEDULED
      Schedule: "cron(0 19 * * ? *)"
      Actions:
        - JobName: !Sub ${LogicalName}-ga4-to-s3-ingestion-job
      StartOnCreation: true
      Description: !Sub Scheduled trigger for ${LogicalName} GA4 to S3 data ingestion job

Outputs:
  GlueRoleArn:
    Description: ARN of the IAM role for AWS Glue jobs
    Value: !GetAtt IAMRoleForGlue.Arn

  SecretsManagerArn:
    Description: ARN of the Secrets Manager secret for Google Analytics credentials
    Value: !Ref SecretsManager

  GlueTableName:
    Description: Name of the Glue Table for GA4 core reports
    Value: !Ref GlueTableGA4CoreReports

  GlueConnectionName:
    Description: Name of the Google Analytics 4 Glue Connection
    Value: !Ref GlueConnection

  GA4IngestionJobName:
    Description: Name of the Google Analytics 4 to S3 data ingestion job
    Value: !Sub ${LogicalName}-ga4-to-s3-ingestion-job

  VisualETLLambdaArn:
    Description: ARN of the Visual ETL Lambda function
    Value: !GetAtt VisualETLLambdaFunction.Arn

  GA4IngestionGitIntegrationEnabled:
    Description: Whether Git integration is enabled for GA4 to S3 data ingestion job
    Value: !If
      - HasGitRepository
      - "true"
      - "false"

  GA4IngestionScheduleName:
    Condition: IsScheduleEnabled
    Description: Name of the scheduled trigger for GA4 to S3 data ingestion job
    Value: !Ref GlueJobScheduleTrigger

  GA4IngestionScheduleEnabled:
    Description: Whether scheduled execution is enabled for GA4 to S3 data ingestion job
    Value: !Ref ScheduleEnabled

  GA4IngestionScheduleExpression:
    Description: Cron expression for GA4 to S3 data ingestion schedule (4:00 AM JST / 19:00 UTC)
    Value: "cron(0 19 * * ? *)"

  CloudWatchAlarmLambdaStackId:
    Description: Stack ID of the Lambda CloudWatch Alarm stack
    Value: !Ref CloudWatchAlarmLambda

  CloudWatchAlarmEstimatedChargesName:
    Description: Name of the CloudWatch Alarm for estimated charges
    Value: !Ref CloudWatchAlarmEstimatedCharges

  CloudWatchAlarmGlueStackId:
    Description: Stack ID of the Glue CloudWatch Alarm stack
    Value: !Ref CloudWatchAlarmGlue

Conditions:
  HasGitRepository: !And
    - !Not [!Equals [!Ref GitRepository, ""]]
    - !Not [!Equals [!Ref GitOwner, ""]]
    - !Not [!Equals [!Ref GitToken, ""]]
  IsScheduleEnabled: !Equals [!Ref ScheduleEnabled, "true"]
