AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/analytics/googleanalytics creates a data analytics flow for Google Analytics.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'AppFlow Configuration'
        Parameters: 
          - AuthCode
          - ClientId
          - ClientSecret
          - EntityName
          - S3BucketNameForSource
          - ScheduleRate
      - Label: 
          default: 'Glue Configuration'
        Parameters: 
          - GlueDatabaseName
          - GlueJobNumberOfWorkers
          - GlueJobWorkerType
          - GlueRegistoryArn
          - S3BucketNameForGlue
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalName
          - Environment 
          - TagKey
          - TagValue

Parameters:
  AuthCode:
    Type: String
    AllowedPattern: .+
    NoEcho: true
    Description: The code provided by the connector when it has been authenticated [required]
  ClientId:
    Type: String
    AllowedPattern: .+
    Description: The identifier for OAuth2 [required]
  ClientSecret:
    Type: String
    AllowedPattern: .+
    NoEcho: true
    Description: The client secret used by the OAuth client to authenticate [required]
  EntityName:
    Type: String
    AllowedPattern: .+
    Description: The entity name (path) of Google Analytics [required]
  GlueDatabaseName: 
    Type: String
    Default: datalake
    AllowedPattern: '[a-z0-9\_]+'
    MinLength: 1
    MaxLength: 20
    Description: Prefix that is used for the created resources (20 chars, a-z, 0-9 and _ only) [required]
  GlueJobNumberOfWorkers:
    Type: Number
    Default: 2
    MinValue: 2
    Description: The number of workers of a defined workerType that are allocated when a job runs [required] 
  GlueJobWorkerType:
    Type: String
    Default: G.1X
    AllowedValues:
      - G.025X
      - G.1X
      - G.2X
      - G.4X
      - G.8X
      - Z.2X
    Description: The type of predefined worker that is allocated when a job runs [required] 
  GlueRegistoryArn:
    Type: String
    AllowedPattern: arn:aws(-(cn|us-gov|iso(-[bef])?))?:glue:.*
    Description: The Amazon Resource Name (ARN) of the registry [required]
  LogicalName: 
    Type: String
    Default: GoogleAnalytics
    Description: The custom prefix name [required]
  ScheduleRate:
    Type: Number
    Default: 24
    MinValue: 24
    Description: The rate at which the scheduled flow will run [required]
  S3BucketNameForGlue:
    Type: String
    AllowedPattern: .+
    Description: The bucket name Glue uses [required]
  S3BucketNameForSource:
    Type: String
    AllowedPattern: .+
    Description: The bucket name data are stored [required]
  SNSForAlertArn:
    Type: String
    Default: ''
  SNSForDeploymentArn:
    Type: String
    Default: ''
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-samples
    AllowedPattern: .+

Conditions:
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']
  Development: !Equals [ !Ref Environment, development]

Resources:
  # Nested Stack
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.1
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.1
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # AppFlow
  AppFlow:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        AuthCode: !Ref AuthCode
        ClientId: !Ref ClientId
        ClientSecret: !Ref ClientSecret
        EntityName: !Ref EntityName
        ScheduleRate: !Ref ScheduleRate
        S3BucketName: !Ref S3BucketNameForSource
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/analytics/googleanalytics-appflow.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/analytics/googleanalytics-appflow.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # Glue
  Glue:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        DatabaseName: !Ref GlueDatabaseName
        GlueBucketName: !Ref S3BucketNameForGlue
        GlueJobNumberOfWorkers: !Ref GlueJobNumberOfWorkers
        GlueJobWorkerType: !Ref GlueJobWorkerType
        GlueRegistoryArn: !Ref GlueRegistoryArn
        SourceBucketName: !GetAtt AppFlow.Outputs.DistinationBucket
        LogicalName: !Ref LogicalName
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/analytics/googleanalytics-glue.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/analytics/googleanalytics-glue.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue