AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-cloudformation-templates/analytics creates Google Analytics data processing infrastructure.

Globals:
  Function:
    Architectures:
      - arm64
    Handler: lambda_function.lambda_handler
    Runtime: python3.13
    Tracing: Active

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Analytics Configuration"
        Parameters:
          - GoogleAnalyticsPropertyId
          - GoogleAnalyticsAccountId
          - GoogleAnalyticsClientSecret

          - GlueJobTimeout
          - GlueWorkerCount
      - Label:
          default: "Notification Configuration"
        Parameters:
          - AlarmLevel
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label:
          default: "Git Integration Configuration"
        Parameters:
          - GitRepository
          - GitOwner
          - GitBranch
          - GitFolder
          - GitToken
      - Label:
          default: "Schedule Configuration"
        Parameters:
          - ScheduleEnabled
      - Label:
          default: "Tag Configuration"
        Parameters:
          - LogicalName
          - Environment
          - TagKey
          - TagValue

Parameters:
  AlarmLevel:
    Type: String
    Default: NOTICE
    AllowedValues:
      - NOTICE
      - WARNING
    Description: The alarm level of CloudWatch alarms
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - production
      - test
      - development
    Description: The deployment environment
  GlueJobTimeout:
    Type: Number
    Default: 60
    MinValue: 1
    MaxValue: 2880
    Description: Google Analytics Glue Job timeout in minutes
  GlueWorkerCount:
    Type: Number
    Default: 5
    MinValue: 2
    MaxValue: 100
    Description: Number of Glue workers for Google Analytics processing
  GoogleAnalyticsAccountId:
    Type: String
    Default: ""
    Description: Google Analytics 4 Account ID
  GoogleAnalyticsClientSecret:
    Type: String
    NoEcho: true
    Default: ""
    Description: The Google Analytics 4 OAuth2 Client Secret
  GoogleAnalyticsPropertyId:
    Type: String
    Default: ""
    Description: The Google Analytics 4 Property ID (also used as Client ID)
  LogicalName:
    Type: String
    Default: analytics
    MinLength: 3
    MaxLength: 50
    AllowedPattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
    Description: The custom prefix name for resources [required]
  SNSForAlertArn:
    Type: String
    Default: ""
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: ""
    Description: The Amazon SNS topic ARN for deployment information
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
    Description: The tag key for resource tagging
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+
    Description: The tag value for resource tagging
  GitRepository:
    Type: String
    Default: ""
    Description: Git repository URL for Visual ETL job source control (optional)
  GitOwner:
    Type: String
    Default: ""
    Description: Git repository owner/organization name (optional)
  GitBranch:
    Type: String
    Default: main
    Description: Git branch for Visual ETL job source control
  GitFolder:
    Type: String
    Default: glue-jobs
    Description: Folder path in Git repository for Visual ETL job storage
  GitToken:
    Type: String
    NoEcho: true
    Default: ""
    Description: GitHub/GitLab personal access token for authentication (optional)
  ScheduleEnabled:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable scheduled execution of the Glue job at 4:00 AM JST (UTC+9) daily$'

Conditions:
  CreateSNSForAlert: !Equals [!Ref SNSForAlertArn, ""]
  CreateSNSForDeployment: !Equals [!Ref SNSForDeploymentArn, ""]
  HasGoogleAnalyticsConfig: !And
    - !Not [!Equals [!Ref GoogleAnalyticsPropertyId, ""]]
    - !Not [!Equals [!Ref GoogleAnalyticsAccountId, ""]]
    - !Not [!Equals [!Ref GoogleAnalyticsClientSecret, ""]]
  HasGitIntegration: !And
    - !Not [!Equals [!Ref GitRepository, ""]]
    - !Not [!Equals [!Ref GitOwner, ""]]
    - !Not [!Equals [!Ref GitToken, ""]]

Resources:
  # Nested Stacks
  GlueForGoogleAnalytics:
    Type: AWS::Serverless::Application
    Condition: HasGoogleAnalyticsConfig
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./google-analytics.yaml
      Parameters:
        LogicalName: !Ref LogicalName
        PropertyId: !Ref GoogleAnalyticsPropertyId
        AccountId: !Ref GoogleAnalyticsAccountId
        ClientSecret: !Ref GoogleAnalyticsClientSecret

        GlueJobTimeout: !Ref GlueJobTimeout
        GlueWorkerCount: !Ref GlueWorkerCount
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
        # Pass all required resources as parameters
        RawDataBucketName: !Ref S3BucketForRawData
        IcebergDataBucketName: !Ref S3BucketForIcebergData
        ScriptsBucketName: !Ref S3BucketForScripts
        QueryResultsBucketName: !Ref S3BucketForQueryResults

        AlertTopicArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        GlueDatabaseName: !Ref GlueDatabase
        # Git Integration Settings
        GitRepository: !Ref GitRepository
        GitOwner: !Ref GitOwner
        GitBranch: !Ref GitBranch
        GitFolder: !Ref GitFolder
        GitToken: !Ref GitToken
        ScheduleEnabled: !Ref ScheduleEnabled
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

  # IAM Roles
  # Note: 将来のオーケストレーション拡張時には以下のリソースを追加:
  # - IAMRoleForStepFunctions (Step Functions実行用)
  # - LambdaOrchestratorFunction (ワークフロー統制用)
  # - StepFunctionsStateMachine (複数データソース統合用)

  # Other Resources (alphabetically grouped by logical relationship)
  # Glue Data Catalog Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub ${LogicalName}_db
        Description: !Sub Database for ${LogicalName} analytics platform

  # S3 Buckets
  S3BucketForIcebergData:
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${LogicalName}-iceberg-data-${AWS::Region}-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 365
                StorageClass: STANDARD_IA
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 1095
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VersioningConfiguration:
        Status: Enabled

  S3BucketForQueryResults:
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${LogicalName}-query-results-${AWS::Region}-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - Id: DeleteQueryResultsAfter30Days
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  S3BucketForRawData:
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${LogicalName}-raw-data-${AWS::Region}-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - Id: DeleteRawDataAfter7Days
            Status: Enabled
            ExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  S3BucketForScripts:
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${LogicalName}-scripts-${AWS::Region}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

  # SNS Topics
  SNSForAlert:
    Condition: CreateSNSForAlert
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.14
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.14
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

Outputs:
  # Google Analytics Stack Outputs
  GoogleAnalyticsStackId:
    Condition: HasGoogleAnalyticsConfig
    Description: Stack ID of the Google Analytics child stack
    Value: !Ref GlueForGoogleAnalytics

  # TODO: Uncomment after Glue Job and Scheduler are deployed in child stack
  # GoogleAnalyticsGlueJobName:
  #   Description: Name of the Google Analytics Glue Job from child stack
  #   Value: !GetAtt GlueForGoogleAnalytics.Outputs.GlueJobName

  # GoogleAnalyticsSchedulerName:
  #   Description: Name of the Google Analytics EventBridge Scheduler from child stack
  #   Value: !GetAtt GlueForGoogleAnalytics.Outputs.SchedulerName

  # Core Infrastructure Outputs (for reference)

  RawDataBucketName:
    Description: Name of the S3 bucket for raw data staging
    Value: !Ref S3BucketForRawData

  IcebergDataBucketName:
    Description: Name of the S3 bucket for Iceberg data storage
    Value: !Ref S3BucketForIcebergData

  ScriptsBucketName:
    Description: Name of the S3 bucket for Glue scripts storage
    Value: !Ref S3BucketForScripts

  QueryResultsBucketName:
    Description: Name of the S3 bucket for Athena query results
    Value: !Ref S3BucketForQueryResults

  SecretsManagerArn:
    Condition: HasGoogleAnalyticsConfig
    Description: ARN of the Secrets Manager secret for Google Analytics credentials
    Value: !GetAtt GlueForGoogleAnalytics.Outputs.SecretsManagerArn

  AlertTopicArn:
    Description: ARN of the SNS topic for alerts
    Value: !If
      - CreateSNSForAlert
      - !GetAtt SNSForAlert.Outputs.SNSTopicArn
      - !Ref SNSForAlertArn

  GlueDatabaseName:
    Description: Name of the Glue Data Catalog database
    Value: !Ref GlueDatabase

  GitIntegrationEnabled:
    Condition: HasGoogleAnalyticsConfig
    Description: Whether Git integration is enabled for Visual ETL Job
    Value: !If
      - HasGitIntegration
      - "true"
      - "false"
