AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-cloudformation-templates/analytics/template creates analytics resources.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Google Analytics 4 Configuration"
        Parameters:
          - GoogleAnalyticsAccountId
          - GoogleAnalyticsClientSecret
          - GoogleAnalyticsPropertyId
          - GoogleAnalyticsPropertyNumber
          - LogicalName
      - Label:
          default: "Tag Configuration"
        Parameters:
          - TagKey
          - TagValue

Parameters:
  GoogleAnalyticsAccountId:
    Type: String
    AllowedPattern: .+
    Description: The Google Analytics 4 Account ID [required]
  GoogleAnalyticsClientSecret:
    Type: String
    NoEcho: true
    Description: The client secret for Google Analytics 4 OAuth application [required]
  GoogleAnalyticsPropertyId:
    Type: String
    AllowedPattern: .+
    Description: The Google Analytics 4 Client ID [required]
  GoogleAnalyticsPropertyNumber:
    Type: String
    AllowedPattern: .+
    Description: The Google Analytics 4 Property Number [required]
  LogicalName:
    Type: String
    Default: googleanalytics
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    Description: The custom prefix name for resources (lowercase alphanumeric and hyphens only) [required]
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  # Nested Stacks
  GoogleAnalyticsConnector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./glue-google-analytics-connector.yaml
      Parameters:
        LogicalName: !Ref LogicalName
        PropertyId: !Ref GoogleAnalyticsPropertyId
        ClientSecret: !Ref GoogleAnalyticsClientSecret
        AccountId: !Ref GoogleAnalyticsAccountId
        PropertyNumber: !Ref GoogleAnalyticsPropertyNumber
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue

Outputs:
  # Resource ARNs (alphabetical order)

  GoogleAnalyticsS3BucketForDataArn:
    Description: ARN of the S3 bucket for Google Analytics 4 raw data storage
    Value: !GetAtt GoogleAnalyticsConnector.Outputs.S3BucketForDataArn
  GoogleAnalyticsSecretArn:
    Description: ARN of the AWS Secrets Manager secret for Google Analytics 4
    Value: !GetAtt GoogleAnalyticsConnector.Outputs.SecretsManagerArn

  # Resource Names (alphabetical order)
  GoogleAnalyticsETLJobName:
    Description: Name of the Google Analytics 4 ETL job
    Value: !GetAtt GoogleAnalyticsConnector.Outputs.ETLJobName
  GoogleAnalyticsGlueConnectionName:
    Description: Name of the Google Analytics 4 connection
    Value: !GetAtt GoogleAnalyticsConnector.Outputs.GlueConnectionName
