AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/cloudops/applicationinsights creates a group of Amazon CloudWatch Application Insights.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'Notification Configuration'
        Parameters:
          - SNSForAlertArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment
          - TagKey
          - TagValue

Parameters:
  SNSForAlertArn:
    Type: String
    AllowedPattern: .+
    Description: The ARN of an Amazon SNS topic [required] 
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  ApplicationInsights:
    Type: AWS::ApplicationInsights::Application
    Properties:
      AutoConfigurationEnabled: true
      CWEMonitorEnabled: true
      OpsCenterEnabled: true
      OpsItemSNSTopicArn: !Ref SNSForAlertArn
      ResourceGroupName: !Sub ${TagKey}-${TagValue}
      Tags: 
        - Key: environment
          Value: !Ref Environment       
        - Key: !Ref TagKey
          Value: !Ref TagValue