AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/cloudops/resiliencehub sets AWS ResilienceHub.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Notification Configuration'
        Parameters:
          - LogicalNamePrefix
          - Environment
          - TagKey
          - TagValue

Parameters:
  LogicalNamePrefix:
    Type: String
    Default: SystemsManager
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  IAMRoleForResilienceHub:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: resiliencehub.amazonaws.com
            Action: sts:AssumeRole
      Description: A role required for AWS Resilience Hub Incident Manager to access related resources.
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSResilienceHubAsssessmentExecutionPolicy
      RoleName: !Sub ${LogicalNamePrefix}-ResilienceHub-${AWS::Region}
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  ResiliencyPolicy:
    Type: AWS::ResilienceHub::ResiliencyPolicy
    Properties:
      DataLocationConstraint: AnyLocation
      Policy:
        AZ:
          RpoInSecs: 3600
          RtoInSecs: 14400
        Hardware:
          RpoInSecs: 3600
          RtoInSecs: 14400
        Software:
          RpoInSecs: 3600
          RtoInSecs: 14400
      PolicyDescription: !Sub The resiliency policy for ${AWS::StackName}
      PolicyName: !Sub target-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue 
      Tier: CoreServices