AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/cloudops sets basic configurations for CloudOps.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Systems ManagerConfiguration
        Parameters:
          - SSMAdminAccountId
          - SSMIgnoreResourceConflicts
          - SSMOrganizationID
          - SSMPatchingAt
      - Label:
          default: Systems Manager Incident Manager Configuration
        Parameters:
          - IncidentManager
          - IncidentManagerAlias
          - IncidentManagerChatbotSnsArn
          - IncidentManagerDisplayName
          - IncidentManagerDurationInMinutes
          - IncidentManagerEmail
          - IncidentPhoneNumber
          - IncidentManagerWorkloadName
      - Label:
          default: CloudWatch Application Insight Configuration
        Parameters:
          - ApplicationInsights
      - Label:
          default: Notofication Configuration
        Parameters:
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label:
          default: Tag Configuration
        Parameters:
          - Environment
          - TagKey
          - TagValue
Parameters:
  ApplicationInsights:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable Amazon CloudWatch Application Insights [required]
  IncidentManager:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable AWS Systems Manager Incident Manager [required]
  IncidentManagerAlias:
    Type: String
    Default: administrator
    AllowedPattern: ^[a-z0-9_\-]*$
    Description: The unique and identifiable alias of the contact or escalation plan [required]
  IncidentManagerChatbotSnsArn:
    Type: String
    Default: ''
    Description: The SNS targets that AWS Chatbot uses to notify the chat channel of updates to an incident
  IncidentManagerDisplayName:
    Type: String
    Default: Administrator
    AllowedPattern: ^[\p{L}\p{Z}\p{N}_.\-]*$
    Description: The full name of the contact or escalation plan [required]
  IncidentManagerDurationInMinutes:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 30
    Description: The time to wait until beginning the next stage [required]
  IncidentManagerEmail:
    Type: String
    Default: ''
    Description: The email address
  IncidentPhoneNumber:
    Type: String
    Default: ''
    Description: The Phone number
  IncidentManagerWorkloadName:
    Type: String
    Default: Workload
    AllowedPattern: .+
    Description: The workload name [required]
  SSMAdminAccountId:
    Type: String
    Default: ''
    Description: AWS Account ID of the primary account (the account from which AWS Systems Manager Automation will be initiated)
  SSMIgnoreResourceConflicts:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED
  SSMOrganizationID:
    Type: String
    Default: ''
    Description: AWS Organizations ID
  SSMPatchingAt:
    Type: Number
    Default: 3
    MinValue: 0
    MaxValue: 23
    Description: Daily patching time (H) [required]
  SNSForAlertArn:
    Type: String
    Default: ''
  SNSForDeploymentArn:
    Type: String
    Default: ''
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateApplicationInsights: !Equals
    - !Ref ApplicationInsights
    - ENABLED
  CreateIncidentManager: !Equals
    - !Ref IncidentManager
    - ENABLED
  CreateSNSForAlert: !Equals
    - !Ref SNSForAlertArn
    - ''
  CreateSNSForDeployment: !Equals
    - !Ref SNSForDeploymentArn
    - ''
  Development: !Equals
    - !Ref Environment
    - development

Resources:
  DevOpsGuru:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/cloudops/devopsguru.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/cloudops/devopsguru.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  SystemsManager:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        AdminAccountId: !Ref SSMAdminAccountId
        IgnoreResourceConflicts: !Ref SSMIgnoreResourceConflicts
        OrganizationID: !Ref SSMOrganizationID
        PatchingAt: !Ref SSMPatchingAt
        LogicalNamePrefix: !Ref AWS::StackName
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        SNSForDeploymentArn: !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/cloudops/ssm.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/cloudops/ssm.yaml
  SystemsManagerIncidentManager:
    Condition: CreateIncidentManager
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        Alias: !Ref IncidentManagerAlias
        ChatbotSnsArn: !Ref IncidentManagerChatbotSnsArn
        DisplayName: !Ref IncidentManagerDisplayName
        DurationInMinutes: !Ref IncidentManagerDurationInMinutes
        Email: !Ref IncidentManagerEmail
        PhoneNumber: !Ref IncidentPhoneNumber
        WorkloadName: !Ref IncidentManagerWorkloadName
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/cloudops/incidentmanager.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/cloudops/incidentmanager.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  ResourceExplorer:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/cloudops/resourceexplorer.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/cloudops/resourceexplorer.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  ResilienceHub:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        Environment: !Ref Environment
        LogicalNamePrefix: !Ref AWS::StackName
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/cloudops/resiliencehub.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/cloudops/resiliencehub.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchApplicationInsights:
    Condition: CreateApplicationInsights
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        SNSForAlertArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/cloudops/applicationinsights.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/cloudops/applicationinsights.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.1.16
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.1.16
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Description: !Sub Group by ${TagKey} ${TagValue}
      Name: !Sub ${TagKey}-${TagValue}
      ResourceQuery:
        Query:
          TagFilters:
            - Key: !Ref TagKey
              Values:
                - !Ref TagValue
        Type: TAG_FILTERS_1_0
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # OIDC for GitHub
  GitHub:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList: 
        - sts.amazonaws.com
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      ThumbprintList: 
        - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      Url: token.actions.githubusercontent.com
  IAMRoleForGitHubActions:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHub.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:eijikominami/aws-cloudformation-templates:*
      Description: A role required for GitHub Actions to access CodeGuru.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCodeGuruReviewerFullAccess
      Policies:  
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetBucket*
                  - s3:List*
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${S3ForCodeGuruReviewer}'
                  - !Sub 'arn:aws:s3:::${S3ForCodeGuruReviewer}/*'
      RoleName: !Sub ${AWS::StackName}-GitHubActions-${AWS::Region}
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  S3ForCodeGuruReviewer:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub codeguru-reviewer-${AWS::Region}-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationInDays
            ExpirationInDays: 7
            Status: Enabled
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  S3BucketPolicyForS3ForCodeGuruReviewer:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3ForCodeGuruReviewer
      PolicyDocument:
        Version: 2012-10-17
        Id: !Ref S3ForCodeGuruReviewer
        Statement:
          - Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !GetAtt S3ForCodeGuruReviewer.Arn
              - !Join
                - ''
                - - !GetAtt S3ForCodeGuruReviewer.Arn
                  - /*
            Condition:
              Bool: 
                aws:SecureTransport: false
          - Sid: DenyPublicReadACL
            Effect: Deny
            Principal:
              AWS: '*'
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
            Condition:
              StringEquals:
                s3:x-amz-acl:
                  - public-read
                  - public-read-write
                  - authenticated-read
          - Sid: DenyPublicReadGrant
            Effect: Deny
            Principal:
              AWS: '*'
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
            Condition:
              StringEquals:
                s3:x-amz-grant-read:
                  - "*http://acs.amazonaws.com/groups/global/AllUsers*"
                  - "*http://acs.amazonaws.com/groups/global/AuthenticatedUsers*"
          - Sid: DenyPublicListACL
            Effect: Deny
            Principal:
              AWS: '*'
            Action: s3:PutBucketAcl
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
            Condition:
              StringEquals:
                s3:x-amz-acl:
                  - public-read
                  - public-read-write
                  - authenticated-read
          - Sid: DenyPublicListGrant
            Effect: Deny
            Principal:
              AWS: '*'
            Action: s3:PutBucketAcl
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
            Condition:
              StringEquals:
                s3:x-amz-grant-read:
                  - "*http://acs.amazonaws.com/groups/global/AllUsers*"
                  - "*http://acs.amazonaws.com/groups/global/AuthenticatedUsers*"
          - Sid: DenyInSecureRequest
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
          - Sid: AllowS3WriteAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: s3:PutObject
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
          - Sid: DenyS3ReadAccess
            Effect: Deny
            Principal: '*'
            Action: s3:GetObject
            Resource:
              - !Sub ${S3ForCodeGuruReviewer.Arn}/*
            Condition:
              StringNotLike:
                aws:PrincipalArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/codeguru-reviewer.amazonaws.com/AWSServiceRoleForAmazonCodeGuruReviewer