AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudSAMTemplates/notification/sns creates Amazon SNS and related CloudWatch Alarm.

Parameters:
  TopicName:
    Type: String
    Default: Default
    Description: Amazon SNS Topic name
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref TopicName
      TopicName: !Ref TopicName
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: 
        - !Ref SNSTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Sid is required.
          - Sid: From-My-Account
            Effect: Allow
            # All AWS Services
            Principal:
              AWS: '*'
            # Request with the account
            Condition:
              StringEquals:
                aws:SourceOwner: !Ref AWS::AccountId
            Resource: !Ref SNSTopic
            Action: 'sns:Publish'
          - Sid: From-AWS-Services
            Effect: Allow
            Principal:
              Service:
                - budgets.amazonaws.com
                - events.amazonaws.com
                - codestar-notifications.amazonaws.com
            Resource: !Ref SNSTopic
            Action: 'sns:Publish'
  CloudWatchAlarmSNSNumberOfNotificationsFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmDescription: !Join 
        - ''
        - - '*SNS* ('
          - !GetAtt SNSTopic.TopicName
          - ') で *通知エラー* が発生しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/sns/latest/dg/sns-monitoring-using-cloudwatch.html|CloudWatchを使用したトピックの監視> をご覧ください。'
      AlarmName: !Sub Warning-${TopicName}-SNS-NumberOfNotificationsFailed-Occured
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions: 
        - Name: TopicName
          Value: !GetAtt SNSTopic.TopicName
      EvaluationPeriods: 1
      MetricName: NumberOfNotificationsFailed
      Namespace: AWS/SNS
      OKActions:
        - !Ref SNSTopic
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue

Outputs:
  SNSTopicArn:
    Description: SNS Topic ARN
    Value: !Ref SNSTopic
  SNSTopicName:
    Description: SNS Topic Name
    Value: !GetAtt SNSTopic.TopicName