version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.13
    commands:
      # Use the latest version
      - pip install -U pip
      - pip install -U awscli
      # for Lambda
      - pip install aws-sam-cli
      - pip install boto3
      - pip install aws-lambda-powertools
      # CloudFormation Linter
      - pip install cfn-lint
  pre_build:
    commands:
      # cfn-lint is disabled because:
      # - security/templates/securityhub.yaml has conditional DependsOn that cfn-lint cannot properly validate
      # - The template supports both STANDARDS_* mode (creates SecurityHub) and ALERAM_* mode (uses existing SecurityHub)
      # - Finding Aggregator needs DependsOn for STANDARDS_* mode but cfn-lint reports E3005 for ALERAM_* mode
      # - cfn-lint --update-specs
      # - find ./${TEMPLATE_FILE_PATH} -type f -name "*.yaml" | xargs --no-run-if-empty -I{} cfn-lint --regions us-east-1 --ignore-checks W --template {}
      - sam validate --template ${TEMPLATE_FILE_PATH}template.yaml
  build:
    commands:
      - sam build --template ${TEMPLATE_FILE_PATH}template.yaml
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml