version: 0.2

env:
  variables:
    SOURCE_CODE_URL: https://github.com/eijikominami/aws-cloudformation-templates
    APP_ARN_PREFIX: arn:aws:serverlessrepo:us-east-1:172664222583:applications

phases:
  install:
    runtime-versions:
       python: 3.13
    commands:
      # Install AWS SAM CLI
      - pip install -U aws-sam-cli awscli
  pre_build:
    commands:
      # Extract semantic version from tag
      - export SEMANTIC_VERSION=`echo ${CODEBUILD_WEBHOOK_TRIGGER} | sed -r 's/tag\/v([0-9\.]+).*-rc(.*)/\1/'`
      - echo "Semantic Version:" $SEMANTIC_VERSION
      # Upload LICENSE to S3 (required by all templates)
      - aws s3 cp LICENSE s3://${BUCKET_NAME}/LICENSE
      # Upload all README files to S3 (required by sam publish)
      - aws s3 cp monitoring/readme/ s3://${BUCKET_NAME}/readme/ --recursive --exclude "*" --include "*.md"
      - aws s3 cp notification/readme/ s3://${BUCKET_NAME}/readme/ --recursive --exclude "*" --include "*.md"
      - aws s3 cp security/readme/ s3://${BUCKET_NAME}/readme/ --recursive --exclude "*" --include "*.md"
      - aws s3 cp security-config-rules/delete-resources-without-required-tags.md s3://${BUCKET_NAME}/readme/
      - aws s3 cp network/readme/ s3://${BUCKET_NAME}/readme/ --recursive --exclude "*" --include "*.md"
  build:
    commands:
      # Package templates with Lambda functions (CodeUri needs to be S3 URI for sam publish)
      - |
        echo "Packaging security-config-rules template..."
        sam package \
          --template-file security-config-rules/sam-app/template.yaml \
          --output-template-file security-config-rules/sam-app/packaged.yaml \
          --s3-bucket ${BUCKET_NAME} \
          --s3-prefix security-config-rules \
          --region us-east-1
        echo "✅ Packaged security-config-rules template"
      # Publish all templates using sam publish with semantic version
      - |
        FAILED_PUBLISH_COUNT=0
        FAILED_PUBLISH_LIST=""
        
        for template in \
          monitoring/sam-app/acm.yaml \
          monitoring/sam-app/amplify.yaml \
          monitoring/sam-app/appflow.yaml \
          monitoring/sam-app/appstream.yaml \
          monitoring/sam-app/application-elb.yaml \
          monitoring/sam-app/apigateway.yaml \
          monitoring/sam-app/codebuild.yaml \
          monitoring/sam-app/config.yaml \
          monitoring/sam-app/directoryservice.yaml \
          monitoring/sam-app/dynamodb-throttle.yaml \
          monitoring/sam-app/dynamodb.yaml \
          monitoring/sam-app/ec2.yaml \
          monitoring/sam-app/ec2-cwagent.yaml \
          monitoring/sam-app/ecs.yaml \
          monitoring/sam-app/elasticsearch.yaml \
          monitoring/sam-app/elementallink.yaml \
          monitoring/sam-app/events.yaml \
          monitoring/sam-app/glue.yaml \
          monitoring/sam-app/kinesis.yaml \
          monitoring/sam-app/firehose.yaml \
          monitoring/sam-app/lambda.yaml \
          monitoring/sam-app/mediaconnect-source.yaml \
          monitoring/sam-app/medialive.yaml \
          monitoring/sam-app/mediaconvert.yaml \
          monitoring/sam-app/mediastore.yaml \
          monitoring/sam-app/natgateway.yaml \
          monitoring/sam-app/network-elb.yaml \
          monitoring/sam-app/privateendpoints.yaml \
          monitoring/sam-app/route53-resolver.yaml \
          monitoring/sam-app/sns.yaml \
          monitoring/sam-app/ssm-command.yaml \
          monitoring/sam-app/transitgateway.yaml \
          monitoring/sam-app/transitgateway-attachment.yaml \
          monitoring/sam-app/vpn.yaml \
          monitoring/sam-app/workspaces.yaml \
          notification/sam-app/sns.yaml \
          notification/sam-app/events.yaml \
          security/templates/iam.yaml \
          security/sam-app/transfer-sns-topic.yaml \
          security-config-rules/sam-app/packaged.yaml \
          network/templates/az.yaml; do
          echo "Publishing ${template}..."
          if sam publish --template ${template} --semantic-version ${SEMANTIC_VERSION} --region us-east-1; then
            echo "✅ Successfully published ${template}"
          else
            echo "❌ Failed to publish ${template}"
            FAILED_PUBLISH_COUNT=$((FAILED_PUBLISH_COUNT + 1))
            FAILED_PUBLISH_LIST="${FAILED_PUBLISH_LIST}\n  - ${template}"
          fi
        done
        
        if [ $FAILED_PUBLISH_COUNT -gt 0 ]; then
          echo ""
          echo "=========================================="
          echo "❌ ${FAILED_PUBLISH_COUNT} template(s) failed to publish:"
          echo -e "${FAILED_PUBLISH_LIST}"
          echo "=========================================="
          exit 1
        else
          echo ""
          echo "=========================================="
          echo "✅ All templates published successfully"
          echo "=========================================="
        fi
  post_build:
    commands:
      # Set public access policy for all applications
      - |
        FAILED_POLICY_COUNT=0
        FAILED_POLICY_LIST=""
        
        for app_id in \
          cloudwatch-alarm-about-acm \
          cloudwatch-alarm-about-amplify \
          cloudwatch-alarm-about-appflow \
          cloudwatch-alarm-about-appstream \
          cloudwatch-alarm-about-application-elb \
          cloudwatch-alarm-about-apigateway \
          cloudwatch-alarm-about-codebuild \
          cloudwatch-alarm-about-config \
          cloudwatch-alarm-about-directoryservice \
          cloudwatch-alarm-about-dynamodb-throttle \
          cloudwatch-alarm-about-dynamodb \
          cloudwatch-alarm-about-ec2 \
          cloudwatch-alarm-about-ec2-cwagent \
          cloudwatch-alarm-about-ecs \
          cloudwatch-alarm-about-elasticsearch \
          cloudwatch-alarm-about-elementallink \
          cloudwatch-alarm-about-events \
          cloudwatch-alarm-about-glue \
          cloudwatch-alarm-about-kinesis-data-streams \
          cloudwatch-alarm-about-kinesis-data-firehose \
          cloudwatch-alarm-about-lambda \
          cloudwatch-alarm-about-mediaconnect-source \
          cloudwatch-alarm-about-medialive \
          cloudwatch-alarm-about-mediaconvert \
          cloudwatch-alarm-about-mediastore \
          cloudwatch-alarm-about-natgateway \
          cloudwatch-alarm-about-network-elb \
          cloudwatch-alarm-about-privateendpoints \
          cloudwatch-alarm-about-route53-resolver \
          cloudwatch-alarm-about-sns \
          cloudwatch-alarm-about-ssm-command \
          cloudwatch-alarm-about-transitgateway \
          cloudwatch-alarm-about-transitgateway-attachment \
          cloudwatch-alarm-about-vpn \
          cloudwatch-alarm-about-workspaces \
          sns-topic \
          eventbridge-rules \
          iam-access-analyzer \
          transfer-alert-topic \
          delete-resources-without-required-tags \
          availability-zone; do
          echo "Setting policy for ${app_id}..."
          if aws serverlessrepo put-application-policy \
            --application-id ${APP_ARN_PREFIX}/${app_id} \
            --statements Principals='*',Actions=Deploy \
            --region us-east-1; then
            echo "✅ Successfully set policy for ${app_id}"
          else
            echo "❌ Failed to set policy for ${app_id}"
            FAILED_POLICY_COUNT=$((FAILED_POLICY_COUNT + 1))
            FAILED_POLICY_LIST="${FAILED_POLICY_LIST}\n  - ${app_id}"
          fi
        done
        
        if [ $FAILED_POLICY_COUNT -gt 0 ]; then
          echo ""
          echo "=========================================="
          echo "❌ ${FAILED_POLICY_COUNT} application(s) failed to set policy:"
          echo -e "${FAILED_POLICY_LIST}"
          echo "=========================================="
          exit 1
        else
          echo ""
          echo "=========================================="
          echo "✅ All application policies set successfully"
          echo "=========================================="
        fi