version: 0.2

env:
  variables:
    AMPLIFY_SRC_DIR: amplify/templates
    AMPLIFY_DIST_DIR: aws-cloudformation-templates/amplify
    ANALYTICS_SRC_DIR: analytics/sam-app
    ANALYTICS_DIST_DIR: aws-cloudformation-templates/analytics
    CICD_SRC_DIR: cicd/templates
    CICD_DIST_DIR: aws-cloudformation-templates/cicd
    CLOUDOPS_SRC_DIR: cloudops/templates
    CLOUDOPS_DIST_DIR: aws-cloudformation-templates/cloudops
    EC2_SRC_DIR: web-servers/templates
    EC2_DIST_DIR: aws-cloudformation-templates/web-servers
    EDGE_SRC_DIR: edge/templates
    EDGE_DIST_DIR: aws-cloudformation-templates/edge
    EUC_SRC_DIR: euc/templates
    EUC_DIST_DIR: aws-cloudformation-templates/euc
    GLOBAL_SRC_DIR: global/templates
    GLOBAL_DIST_DIR: aws-cloudformation-templates/global
    HOSTING_SRC_DIR: static-website-hosting/templates
    HOSTING_DIST_DIR: aws-cloudformation-templates/static-website-hosting
    IDENTITY_SRC_DIR: identity/templates
    IDENTITY_DIST_DIR: aws-cloudformation-templates/identity
    MEDIA_SRC_DIR: media/templates
    MEDIA_DIST_DIR: aws-cloudformation-templates/media
    MIGRATION_SRC_DIR: migration/templates
    MIGRATION_DIST_DIR: aws-cloudformation-templates/migration
    AIML_SRC_DIR: aiml/templates
    AIML_DIST_DIR: aws-cloudformation-templates/aiml
    MONITORING_SRC_DIR: monitoring/sam-app
    MONITORING_DIST_DIR: aws-cloudformation-templates/monitoring
    NETWORK_SRC_DIR: network/templates
    NETWORK_DIST_DIR: aws-cloudformation-templates/network
    NOTIFICATION_SAM_SRC_DIR: notification/sam-app
    NOTIFICATION_CFN_SRC_DIR: notification/templates
    NOTIFICATION_DIST_DIR: aws-cloudformation-templates/notification
    SECURITY_SRC_DIR: security/templates
    SECURITY_DIST_DIR: aws-cloudformation-templates/security
    SECURITY_CONFIG_RULES_SRC_DIR: security-config-rules/sam-app
    SECURITY_CONFIG_RULES_DIST_DIR: aws-cloudformation-templates/security-config-rules
    SHARED_SRC_DIR: shared/templates
    SHARED_DIST_DIR: aws-cloudformation-templates/shared
    STORAGE_SRC_DIR: storage/templates
    STORAGE_DIST_DIR: aws-cloudformation-templates/storage

phases:
  install:
    runtime-versions:
       python: 3.9
    commands:
      # Use the latest version
      - pip install -U pip
      - pip install -U awscli
      # for Lambda
      - pip install aws-sam-cli
      - pip install requests
      - pip install aws_xray_sdk
      # CloudFormation Linter
      - pip install cfn-lint
  pre_build:
    commands:
      - find ./ -type f -name "*.yaml" | xargs --no-run-if-empty -I{} cfn-lint --regions us-east-1 --ignore-checks W --template {}
      - aws s3 rm s3://${BUCKET_NAME}/${AMPLIFY_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${ANALYTICS_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${CICD_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${CLOUDOPS_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${EC2_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${EDGE_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${EUC_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${GLOBAL_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${HOSTING_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${IDENTITY_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${MEDIA_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${MIGRATION_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${AIML_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${MONITORING_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${NETWORK_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${NOTIFICATION_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${SECURITY_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${SECURITY_CONFIG_RULES_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${SHARED_DIST_DIR}/ --recursive
      - aws s3 rm s3://${BUCKET_NAME}/${STORAGE_DIST_DIR}/ --recursive
  build:
    commands:
      - sam validate --template ${ANALYTICS_SRC_DIR}/googleanalytics.yaml
      - sam build --template ${ANALYTICS_SRC_DIR}/googleanalytics.yaml --build-dir ${ANALYTICS_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${ANALYTICS_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${ANALYTICS_DIST_DIR} --output-template-file ${ANALYTICS_SRC_DIR}/googleanalytics-packaged.yaml
      - sam validate --template ${CICD_SRC_DIR}/template.yaml
      - sam build --template ${CICD_SRC_DIR}/template.yaml --build-dir ${CICD_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${CICD_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${CICD_DIST_DIR} --output-template-file ${CICD_SRC_DIR}/packaged.yaml
      - sam validate --template ${NOTIFICATION_SAM_SRC_DIR}/template.yaml
      - sam build --template ${NOTIFICATION_SAM_SRC_DIR}/template.yaml --build-dir ${NOTIFICATION_SAM_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${NOTIFICATION_SAM_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${NOTIFICATION_DIST_DIR} --output-template-file ${NOTIFICATION_SAM_SRC_DIR}/packaged.yaml
      - sam validate --template ${SECURITY_CONFIG_RULES_SRC_DIR}/template.yaml
      - sam build --template ${SECURITY_CONFIG_RULES_SRC_DIR}/template.yaml --build-dir ${SECURITY_CONFIG_RULES_SRC_DIR}/.aws-sam/build
      - sam package --template-file ${SECURITY_CONFIG_RULES_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${SECURITY_CONFIG_RULES_DIST_DIR} --output-template-file ${SECURITY_CONFIG_RULES_SRC_DIR}/packaged.yaml
      - aws cloudformation package --template-file ${EC2_SRC_DIR}/template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix ${EC2_DIST_DIR} --output-template-file ${EC2_SRC_DIR}/packaged.yaml
  post_build:
    commands:
       - aws s3 cp ${AMPLIFY_SRC_DIR}/ s3://${BUCKET_NAME}/${AMPLIFY_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${ANALYTICS_SRC_DIR}/ s3://${BUCKET_NAME}/${ANALYTICS_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${CICD_SRC_DIR}/ s3://${BUCKET_NAME}/${CICD_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${CLOUDOPS_SRC_DIR}/ s3://${BUCKET_NAME}/${CLOUDOPS_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${EC2_SRC_DIR}/ s3://${BUCKET_NAME}/${EC2_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${EDGE_SRC_DIR}/ s3://${BUCKET_NAME}/${EDGE_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${EUC_SRC_DIR}/ s3://${BUCKET_NAME}/${EUC_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${GLOBAL_SRC_DIR}/ s3://${BUCKET_NAME}/${GLOBAL_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${HOSTING_SRC_DIR}/ s3://${BUCKET_NAME}/${HOSTING_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${IDENTITY_SRC_DIR}/ s3://${BUCKET_NAME}/${IDENTITY_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${MEDIA_SRC_DIR}/ s3://${BUCKET_NAME}/${MEDIA_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${MIGRATION_SRC_DIR}/ s3://${BUCKET_NAME}/${MIGRATION_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${AIML_SRC_DIR}/ s3://${BUCKET_NAME}/${AIML_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${MONITORING_SRC_DIR}/ s3://${BUCKET_NAME}/${MONITORING_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${NETWORK_SRC_DIR}/ s3://${BUCKET_NAME}/${NETWORK_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${NOTIFICATION_SAM_SRC_DIR}/ s3://${BUCKET_NAME}/${NOTIFICATION_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${NOTIFICATION_CFN_SRC_DIR}/ s3://${BUCKET_NAME}/${NOTIFICATION_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${SECURITY_SRC_DIR}/ s3://${BUCKET_NAME}/${SECURITY_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${SECURITY_CONFIG_RULES_SRC_DIR}/ s3://${BUCKET_NAME}/${SECURITY_CONFIG_RULES_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${SHARED_SRC_DIR}/ s3://${BUCKET_NAME}/${SHARED_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'
       - aws s3 cp ${STORAGE_SRC_DIR}/ s3://${BUCKET_NAME}/${STORAGE_DIST_DIR}/ --recursive --include '*.yaml' --exclude '.aws-sam/*'