AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: aws-cloudformation-templates/security/guardduty sets Amazon GuardDuty.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'GuardDuty Configuration'
        Parameters: 
          - Detector
          - FindingsDestinationBucketArn
          - KmsKeyArn
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - AlarmLevel
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalName
          - Environment
          - TagKey
          - TagValue

Parameters:
  AlarmLevel:
    Type: String
    Default: NOTICE
    AllowedValues:
      - NOTICE
      - WARNING
    Description: The alarm level of CloudWatch alarms
  Detector:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: The GuardDuty detector [required]
  FindingsDestinationBucketArn:
    Type: String
    Default: '' 
    Description: The Amazon S3 bucket ARN for GuardDuty to send findings to
  KmsKeyArn:
    Type: String
    Default: '' 
    Description: The KMS key ARN for GuardDuty to encrypt findings    
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for deployment information
  LogicalName:
    Type: String
    Default: DefaultSecuritySettings
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateDetector: !Equals [ !Ref Detector, ENABLED]
  CreatePublishingDestination: !And [ !Equals [ !Ref Detector, ENABLED], !Not [ !Equals [ !Ref FindingsDestinationBucketArn, '' ] ], !Not [ !Equals [ !Ref KmsKeyArn, '' ] ] ]
  CreateSNSForAlertTransfer: !Not [ !Equals [ !Ref SNSForAlertArn, ''] ]
  CreateSNSForDeploymentTransfer: !Not [ !Equals [ !Ref SNSForDeploymentArn, ''] ]

Resources:
  # Nested Stack
  SNSForAlert:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.24
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        TopicName: !Sub Alert-createdby-${LogicalName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.24
      Parameters:
        TopicName: !Sub Deployment-createdby-${LogicalName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  TransferAlertTopic:
    Condition: CreateSNSForAlertTransfer
    Type: AWS::Serverless::Application
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeploymentTransfer
          - !Ref SNSForDeploymentArn
          - !Ref AWS::NoValue
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        SourceSNSArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        DestinationSNSArn: !Ref SNSForAlertArn
        Environment: !Ref Environment
        LogicalName: TransferGuardDutyTopic
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/transfer-sns-topic
        SemanticVersion: 2.2.24
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # Service-linked Role
  ServiceLinkedRoleForGuardDuty:
    Condition: CreateDetector
    Type: AWS::IAM::ServiceLinkedRole
    Properties: 
      AWSServiceName: guardduty.amazonaws.com
      Description: A service-linked role required for Amazon GuardDuty to access your resources.
  # GuardDuty
  GuardDutyDetector:
    Condition: CreateDetector
    DependsOn:
      - ServiceLinkedRoleForGuardDuty
    Type: AWS::GuardDuty::Detector
    Properties:
      DataSources:
        MalwareProtection: 
          ScanEc2InstanceWithFindings: 
            EbsVolumes: true
        S3Logs:
          Enable: true      
      Enable: true
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  GuardDutyPublishingDestination:
    Condition: CreatePublishingDestination
    Type: AWS::GuardDuty::PublishingDestination
    Properties:
      DestinationProperties: 
        DestinationArn: !Ref FindingsDestinationBucketArn
        KmsKeyArn: !Ref KmsKeyArn
      DestinationType: S3
      DetectorId: !Ref GuardDutyDetector
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # EventBridge for GuardDuty
  CloudWatchEventsForGuardDuty:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub Rule for GuardDuty created by ${AWS::StackName}.
      # MEDIUM or higher
      # https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251
      EventPattern: |
        {
           "source": [
              "aws.guardduty"
           ],
           "detail-type": [
              "GuardDuty Finding"
           ],
           "detail": {
              "severity": [
                 { "numeric": [ ">=", 4 ] }
              ]
           }
        }
      Name: GuardDuty
      State: ENABLED
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: CloudWatchEventsForGuardDuty
  # CloudWatch
  AlarmEventsForGuardDuty:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-events
        SemanticVersion: 2.2.24
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        AlarmLevel: !Ref AlarmLevel
        CustomAlarmName: !Ref AWS::StackName
        SNSTopicArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        EventsRuleName: !Ref CloudWatchEventsForGuardDuty
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue