AWSTemplateFormatVersion: 2010-09-09
Description: AWSCloudFormationTemplates/security/Inspector sets Amazon Macie.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Macie Configuration'
        Parameters:
          - FindingPublishingFrequency
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalNamePrefix
          - Environment
          - TagKey
          - TagValue

Parameters:
  FindingPublishingFrequency:
    Type: String
    Default: SIX_HOURS
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - SIX_HOURS
    Description: The frequency with which Amazon Macie publishes updates to policy findings for an account [required]
  LogicalNamePrefix:
    Type: String
    Default: DefaultSecuritySettings
    AllowedPattern: .+
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  IAMRoleForMacie:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: macie.amazonaws.com
            Action: 'sts:AssumeRole'
      Description: A role required for CloudTrail to access CloudWatch Logs.
      Policies:
        - PolicyName: CustomPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetEventSelectors
                  - cloudtrail:GetTrailStatus
                  - cloudtrail:ListTags
                  - cloudtrail:LookupEvents
                  - iam:ListAccountAliases
                  - organizations:DescribeAccount
                  - organizations:ListAccounts
                  - s3:GetAccountPublicAccessBlock
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:GetBucketPolicy
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketTagging
                  - s3:GetBucketVersioning
                  - s3:GetBucketWebsite
                  - s3:GetEncryptionConfiguration
                  - s3:GetLifecycleConfiguration
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetObjectTagging
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudtrail:CreateTrail
                  - cloudtrail:StartLogging
                  - cloudtrail:StopLogging
                  - cloudtrail:UpdateTrail
                  - cloudtrail:DeleteTrail
                  - cloudtrail:PutEventSelectors
                Resource: arn:aws:cloudtrail:*:*:trail/AWSMacieTrail-DO-NOT-EDIT
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:DeleteBucketPolicy
                  - s3:DeleteBucketWebsite
                  - s3:DeleteObject
                  - s3:DeleteObjectTagging
                  - s3:DeleteObjectVersion
                  - s3:DeleteObjectVersionTagging
                  - s3:PutBucketPolicy
                Resource:
                  - arn:aws:s3:::awsmacie-*
                  - arn:aws:s3:::awsmacietrail-*
                  - arn:aws:s3:::*-awsmacietrail-*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource:
                  - arn:aws:logs:*:*:log-group:/aws/macie/*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource:
                  - arn:aws:logs:*:*:log-group:/aws/macie/*:log-stream:*
      RoleName: !Sub '${LogicalNamePrefix}-Macie-${AWS::Region}'
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  MacieSession:
    Type: AWS::Macie::Session
    Properties:
        FindingPublishingFrequency: !Ref FindingPublishingFrequency
        Status: ENABLED
  MacieLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /aws/macie/classificationjobs
      RetentionInDays: 60
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue