AWSTemplateFormatVersion: 2010-09-09
Transform: 
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/security/SecurityHub sets AWS Security Hub.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Security Hub Configuration'
        Parameters:
          - SecurityHubStandards
      - Label: 
          default: 'Notification Configuration'
        Parameters:
          - NotificationFilterAboutSecurityChecks
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalName
          - Environment
          - TagValue

Parameters:
  NotificationFilterAboutSecurityChecks:
    Type: String
    Default: DENY_ALL
    AllowedValues:
      - DENY_ALL
      - MEDIUM
      - ALLOW_ALL
    Description: The notification filter about Security Hub Security Checks [required]
  LogicalName:
    Type: String
    Default: DefaultSecuritySettings
    Description: The custom prefix name [required]
  SecurityHubStandards:
    Type: CommaDelimitedList
    Default: FSBP, CIS
    AllowedValues:
      - FSBP
      - CIS
      - NIST
      - PCIDSS
    Description: The standard that you want to enable (FSBP, CIS, NIST, PCIDSS)
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for deployment information
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']
  CreateCloudWatchEventsForSecurityHubFindings: !Not [ !Equals [ !Ref NotificationFilterAboutSecurityChecks, DENY_ALL ] ]
  SendAllEvents: !Equals [ !Ref NotificationFilterAboutSecurityChecks, ALLOW_ALL ]

Mappings: 
  SecurityHubStandardsArn: 
    ap-northeast-1:
      FSBP: arn:aws:securityhub:ap-northeast-1::standards/aws-foundational-security-best-practices/v/1.0.0
      CIS: arn:aws:securityhub:ap-northeast-1::standards/cis-aws-foundations-benchmark/v/1.4.0
      NIST: arn:aws:securityhub:ap-northeast-1::standards/nist-800-53/v/5.0.0
      PCIDSS: arn:aws:securityhub:ap-northeast-1::standards/pci-dss/v/3.2.1

Resources:
  # Nested Stack
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.1
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${LogicalName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.1
      Parameters:
        TopicName: !Sub Deployment-createdby-${LogicalName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # AWSServiceRoleForSecurityHub will be created automatically.
  # SecurityHub
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties: 
      EnableDefaultStandards: false
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  'Fn::ForEach::Standards':
    - StandardsArn
    - !Ref SecurityHubStandards
    - SecurityHubStandards${StandardsArn}:
        Type: AWS::SecurityHub::Standard
        Properties:
          StandardsArn: !FindInMap [SecurityHubStandardsArn, !Ref "AWS::Region", !Ref StandardsArn]
  # EventBridge for SecurityHub
  CloudWatchEventsForSecurityHubFindings:
    Condition: CreateCloudWatchEventsForSecurityHubFindings
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub Rule for SecurityHub created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.securityhub
        detail-type: 
          - Security Hub Findings - Imported
        # MEDIUM or higher
        detail:
          findings:
            Compliance:
              Status:
                - FAILED
            Severity:
              Label: !If 
                - SendAllEvents
                - !Ref AWS::NoValue
                - - CRITICAL
                  - HIGH
                  - MEDIUM
      Name: SecurityHub-Findings
      State: ENABLED
      Targets:
        - Arn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
          Id: CloudWatchEventsForSecurityHub
  AlarmEventsForSecurityHubFindings:
    Condition: CreateCloudWatchEventsForSecurityHubFindings
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-events
        SemanticVersion: 2.2.1
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        CustomAlarmName: !Ref AWS::StackName
        SNSTopicArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        EventsRuleName: !Ref CloudWatchEventsForSecurityHubFindings
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue