AWSTemplateFormatVersion: 2010-09-09
Description: AWSCloudFormationTemplates/security/SecurityHub sets AWS Security Hub.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Notification Configuration'
        Parameters:
          - NotificationFilterAboutSecurityChecks
          - SnsTopicARN

Parameters:
  NotificationFilterAboutSecurityChecks:
    Type: String
    Default: DENY_ALL
    AllowedValues:
      - DENY_ALL
      - MEDIUM
      - ALLOW_ALL
    Description: The notification filter about Security Hub Security Checks [required]
  SnsTopicARN:
    Type: String
    AllowedPattern: .+

Conditions:
  CreateCloudWatchEventsForSecurityHubFindings:
   !Not [ !Equals [ !Ref NotificationFilterAboutSecurityChecks, DENY_ALL ] ]
  SendAllEvents:
   !Equals [ !Ref NotificationFilterAboutSecurityChecks, ALLOW_ALL ]

Resources:
  # Service-linked Role
  ServiceLinkedRoleForSecurityHub:
    Type: AWS::IAM::ServiceLinkedRole
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties: 
      AWSServiceName: securityhub.amazonaws.com
      Description: A service-linked role required for AWS Security Hub to access your resources.
  # SecurityHub
  SecurityHub:
    DependsOn:
      - ServiceLinkedRoleForSecurityHub
    Type: AWS::SecurityHub::Hub
  # EventBridge for SecurityHub
  CloudWatchEventsForSecurityHubFindings:
    Condition: CreateCloudWatchEventsForSecurityHubFindings
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub Rule for SecurityHub created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.securityhub
        detail-type: 
          - Security Hub Findings - Imported
        # MEDIUM or higher
        detail:
          findings:
            Compliance:
              Status:
                - FAILED
            Severity:
              Label: !If 
                - SendAllEvents
                - !Ref AWS::NoValue
                - - CRITICAL
                  - HIGH
                  - MEDIUM
      Name: SecurityHub-Findings
      State: ENABLED
      Targets:
        - Arn: !Ref SnsTopicARN
          Id: CloudWatchEventsForSecurityHub