AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/security/SecurityHub sets AWS Security Hub.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Notification Configuration'
        Parameters:
          - NotificationFilterAboutSecurityChecks
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalNamePrefix
          - Environment
          - TagValue

Parameters:
  NotificationFilterAboutSecurityChecks:
    Type: String
    Default: DENY_ALL
    AllowedValues:
      - DENY_ALL
      - MEDIUM
      - ALLOW_ALL
    Description: The notification filter about Security Hub Security Checks [required]
  LogicalNamePrefix:
    Type: String
    Default: DefaultSecuritySettings
    Description: The custom prefix name [required]
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for deployment information
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']
  CreateCloudWatchEventsForSecurityHubFindings: !Not [ !Equals [ !Ref NotificationFilterAboutSecurityChecks, DENY_ALL ] ]
  SendAllEvents: !Equals [ !Ref NotificationFilterAboutSecurityChecks, ALLOW_ALL ]

Resources:
  # Nested Stack
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.0.19
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${LogicalNamePrefix}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.0.19
      Parameters:
        TopicName: !Sub Deployment-createdby-${LogicalNamePrefix}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # Service-linked Role
  ServiceLinkedRoleForSecurityHub:
    Type: AWS::IAM::ServiceLinkedRole
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties: 
      AWSServiceName: securityhub.amazonaws.com
      Description: A service-linked role required for AWS Security Hub to access your resources.
  # SecurityHub
  SecurityHub:
    DependsOn:
      - ServiceLinkedRoleForSecurityHub
    Type: AWS::SecurityHub::Hub
  # EventBridge for SecurityHub
  CloudWatchEventsForSecurityHubFindings:
    Condition: CreateCloudWatchEventsForSecurityHubFindings
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub Rule for SecurityHub created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.securityhub
        detail-type: 
          - Security Hub Findings - Imported
        # MEDIUM or higher
        detail:
          findings:
            Compliance:
              Status:
                - FAILED
            Severity:
              Label: !If 
                - SendAllEvents
                - !Ref AWS::NoValue
                - - CRITICAL
                  - HIGH
                  - MEDIUM
      Name: SecurityHub-Findings
      State: ENABLED
      Targets:
        - Arn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
          Id: CloudWatchEventsForSecurityHub
  AlarmEventsForSecurityHubFindings:
    Condition: CreateCloudWatchEventsForSecurityHubFindings
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-events
        SemanticVersion: 2.0.19
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        CustomAlarmName: !Ref AWS::StackName
        SNSTopicArn: !If
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        EventsRuleName: !Ref CloudWatchEventsForSecurityHubFindings
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue