AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Amazon AppStream

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  Fleet:
    Type: String
    AllowedPattern: .+
    Description: The name of the AppStream Fleet [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+ 

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  Unhealthy:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Workspaces* (${Fleet}) で *異常なステータスを返した Workspaces* があります。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/workspaces/latest/adminguide/cloudwatch-metrics.html|CloudWatch メトリクス を使用して WorkSpaces をモニタリングする> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Workspaces-Unhealthy-${Fleet}
        - !Sub Warning-Workspaces-Unhealthy-${Fleet}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Fleet
          Value: !Ref Fleet
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: InsufficientConcurrencyLimitError
      Namespace: AWS/AppStream
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue