AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Amazon EC2

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom alram name
  ClusterName:
    Type: String
    AllowedPattern: .+
    Description: The ECS Cluster name [required] 
  ServiceName:
    Type: String
    AllowedPattern: .+
    Description: The ECS Service name [required]    
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  UtilizationThreshold:
    Type: Number
    Default: 100
    MinValue: 0
    MaxValue: 100
    Description: The threshold of CPU Utilization [required]

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  EC2StatusCheckFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: '*EC2* で *ステータスチェックエラー* が発生しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html|インスタンスの利用可能な CloudWatch メトリクスのリスト表示> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-EC2-StatusCheckFailed
        - Warning-EC2-StatusCheckFailed
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: StatusCheckFailed
      Namespace: AWS/EC2
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  ECSCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: '*ECS* で *CPU使用率が上昇* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/cloudwatch-metrics.html|Amazon ECS CloudWatch メトリクス> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-ECS-CPU-Overloaded
        - Warning-ECS-CPU-Overloaded
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: ServiceName
          Value: !Ref ServiceName
        - Name: ClusterName
          Value: !Ref ClusterName
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Average
      Threshold: !Ref UtilizationThreshold
      TreatMissingData: notBreaching
  ECSMemoryUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: '*ECS* で *メモリ使用率が上昇* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/cloudwatch-metrics.html|Amazon ECS CloudWatch メトリクス> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-ECS-Memory-Overloaded
        - Warning-ECS-Memory-Overloaded
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: ServiceName
          Value: !Ref ServiceName
        - Name: ClusterName
          Value: !Ref ClusterName
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Average
      Threshold: !Ref UtilizationThreshold
      TreatMissingData: notBreaching