AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Amazon Elasticsearch Service

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  DomainName:
    Type: String
    AllowedPattern: .+
    Description: The domain name [required]
  FreeStorageSpaceThreshold:
    Type: Number
    MinValue: 0
    Description: The threshold of the free storage space (MB) [required]
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  AlarmElasticsearchClusterStatus:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *クラスタ異常が発生* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Elasticsearch-${DomainName}-Cluster-Status
        - !Sub Warning-Elasticsearch-${DomainName}-Cluster-Status
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 1
      MetricName: ClusterStatus.green
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Minimum
      Threshold: 0
      TreatMissingData: notBreaching
  AlarmElasticsearchClusterIndexWritesBlocked:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *書き込みリクエストが拒否* されました。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Cluster-Index-Writes-Blocked
        - !Sub Notice-Elasticsearch-${DomainName}-Cluster-Index-Writes-Blocked
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 1
      MetricName: ClusterIndexWritesBlocked
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmElasticsearchMasterReachableFromNode:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *マスターノードで異常が発生* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Elasticsearch-${DomainName}-Master-Reachable-From-Node
        - !Sub Warning-Elasticsearch-${DomainName}-Master-Reachable-From-Node
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 1
      MetricName: MasterReachableFromNode
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Minimum
      Threshold: 0
      TreatMissingData: notBreaching
  AlarmElasticsearchAutomatedSnapshotFailure:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *自動スナップショットの作成が失敗* しました。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Automated-Snapshot-Failure
        - !Sub Notice-Elasticsearch-${DomainName}-Automated-Snapshot-Failure
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 1
      MetricName: AutomatedSnapshotFailure
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmElasticsearchKibanaHealthyNodes:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *Kibanaの異常が発生* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Elasticsearch-${DomainName}-Kibana-Healthy-Nodes
        - !Sub Warning-Elasticsearch-${DomainName}-Kibana-Healthy-Nodes
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 1
      MetricName: KibanaHealthyNodes
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Minimum
      Threshold: 0
      TreatMissingData: notBreaching
  AlarmElasticsearchFreeStorageSpace:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) の *ディスクの空き容量が減少* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Elasticsearch-${DomainName}-Free-Storage-Space
        - !Sub Warning-Elasticsearch-${DomainName}-Free-Storage-Space
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 1
      MetricName: FreeStorageSpace
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Minimum
      Threshold: !Ref FreeStorageSpaceThreshold
      TreatMissingData: notBreaching
  AlarmElasticsearchMasterCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *マスターノードのCPU使用率が上昇* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Master-CPU-Utilization
        - !Sub Notice-Elasticsearch-${DomainName}-Master-CPU-Utilization
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 15
      MetricName: MasterCPUUtilization
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 50
      TreatMissingData: notBreaching
  AlarmElasticsearchMasterJVMMemoryPressure:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *マスターノードのJVMメモリ負荷率が上昇* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Master-JVM-Memory-Pressure
        - !Sub Notice-Elasticsearch-${DomainName}-Master-JVM-Memory-Pressure
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 15
      MetricName: MasterJVMMemoryPressure
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 80
      TreatMissingData: notBreaching
  AlarmElasticsearchCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *データノードのCPU使用率が上昇* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Data-CPU-Utilization
        - !Sub Notice-Elasticsearch-${DomainName}-Data-CPU-Utilization
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 15
      MetricName: CPUUtilization
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 50
      TreatMissingData: notBreaching
  AlarmElasticsearchJVMMemoryPressure:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *データノードのJVMメモリ負荷率が上昇* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Data-JVM-Memory-Pressure
        - !Sub Notice-Elasticsearch-${DomainName}-Data-JVM-Memory-Pressure
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 15
      MetricName: JVMMemoryPressure
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 80
      TreatMissingData: notBreaching
  AlarmElasticsearchSysMemoryUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Elasticsearch* (${DomainName}) で *データノードのメモリ使用率が上昇* しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Elasticsearch-${DomainName}-Data-Sys-Memory-Utilization
        - !Sub Notice-Elasticsearch-${DomainName}-Data-JVM-Sys-Memory-Utilization
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DomainName
          Value: !Ref DomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      EvaluationPeriods: 15
      MetricName: SysMemoryUtilization
      Namespace: AWS/ES
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 80
      TreatMissingData: notBreaching