AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Amazon Kinesis Data Firehose

Metadata:
  AWS::ServerlessRepo::Application:
    Name: cloudwatch-alarm-about-kinesis-data-firehose
    Description: Create Amazon CloudWatch Alarm about Amazon Kinesis Data Firehose.
    Author: Eiji KOMINAMI
    SpdxLicenseId: MIT
    LicenseUrl: s3://eijikominami-test/LICENSE
    ReadmeUrl: s3://eijikominami-test/readme/cloudwatch-alarm-about-kinesis-data-firehose.md
    Labels: []
    HomePageUrl: https://github.com/eijikominami/aws-cloudformation-templates
    SourceCodeUrl: https://github.com/eijikominami/aws-cloudformation-templates

Parameters:
  AlarmLevel:
    Type: String
    Default: NOTICE
    AllowedValues:
      - NOTICE
      - WARNING
    Description: The alarm level of CloudWatch alarms
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  FirehoseStreamName:
    Type: String
    AllowedPattern: .+
    Description: The Firehose stream name [required]
  OldestRecordAge:
    Type: Number
    Default: 120
    MinValue: 0
    Description: The threshold of the age of the oldest record [required]
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]
  CreateNoticeAlarm: !Not [ !Equals [ !Ref AlarmLevel, WARNING ] ]

Resources:
  AlarmFirehoseDeliveryToElasticsearchDataFreshness:
    Condition: CreateNoticeAlarm
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Firehose* (${FirehoseStreamName}) で *OpenSearch Service への配信遅延が発生* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/firehose/latest/dev/monitoring-with-cloudwatch-metrics.html|CloudWatch メトリクスによる Amazon Data Firehose のモニタリング> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Firehose-${FirehoseStreamName}-Delivery-To-Elasticsearch-Data-Freshness
        - !Sub Notice-Firehose-${FirehoseStreamName}-Delivery-To-Elasticsearch-Data-Freshness
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DeliveryStreamName
          Value: !Ref FirehoseStreamName
      EvaluationPeriods: 1
      MetricName: DeliveryToElasticsearch.DataFreshness
      Namespace: AWS/Firehose
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: !Ref OldestRecordAge
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmFirehoseThrottledGetShardIterator:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Firehose* (${FirehoseStreamName}) で *ThrottledGetShardIteratorが発生* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/firehose/latest/dev/monitoring-with-cloudwatch-metrics.html|CloudWatch メトリクスによる Amazon Data Firehose のモニタリング> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Firehose-${FirehoseStreamName}-Throttled-Get-Shard-Iterator
        - !Sub Warning-Firehose-${FirehoseStreamName}-Throttled-Get-Shard-Iterator
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DeliveryStreamName
          Value: !Ref FirehoseStreamName
      EvaluationPeriods: 1
      MetricName: ThrottledGetShardIterator
      Namespace: AWS/Firehose
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmFirehoseThrottledGetRecords:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Firehose* (${FirehoseStreamName}) で *ThrottledGetRecordsが発生* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/firehose/latest/dev/monitoring-with-cloudwatch-metrics.html|CloudWatch メトリクスによる Amazon Data Firehose のモニタリング> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Firehose-${FirehoseStreamName}-Throttled-Get-Records
        - !Sub Warning-Firehose-${FirehoseStreamName}-Throttled-Get-Records
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DeliveryStreamName
          Value: !Ref FirehoseStreamName
      EvaluationPeriods: 1
      MetricName: ThrottledGetRecords
      Namespace: AWS/Firehose
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmFirehoseDeliveryToElasticsearchFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Firehose* (${FirehoseStreamName}) で *OpenSearch Service へのデータ配信が失敗* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/firehose/latest/dev/monitoring-with-cloudwatch-metrics.html|CloudWatch メトリクスによる Amazon Data Firehose のモニタリング> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Firehose-${FirehoseStreamName}-Delivery-To-Elasticsearch-Failed
        - !Sub Warning-Firehose-${FirehoseStreamName}-Delivery-To-Elasticsearch-Failed
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DeliveryStreamName
          Value: !Ref FirehoseStreamName
      EvaluationPeriods: 1
      MetricName: DeliveryToElasticsearch.Success
      Namespace: AWS/Firehose
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmFirehoseDeliveryToS3Failed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Firehose* (${FirehoseStreamName}) で *S3へのデータ配信が失敗* しています。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/firehose/latest/dev/monitoring-with-cloudwatch-metrics.html|CloudWatch メトリクスによる Amazon Data Firehose のモニタリング> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Firehose-${FirehoseStreamName}-Delivery-To-S3-Failed
        - !Sub Warning-Firehose-${FirehoseStreamName}-Delivery-To-S3-Failed
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DeliveryStreamName
          Value: !Ref FirehoseStreamName
      EvaluationPeriods: 1
      MetricName: DeliveryToS3.Success
      Namespace: AWS/Firehose
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue