AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Amazon Kinesis Data Streams

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'Kinesis Data Streams Configuration'
        Parameters: 
          - KinesisStreamName
          - IteratorAgeMillisecondsThreshold
          - NumberOfPutRecordThreshold
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - AlarmLevel
          - CustomAlarmName
          - SNSTopicArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment 
          - TagKey
          - TagValue

Parameters:
  AlarmLevel:
    Type: String
    Default: NOTICE
    AllowedValues:
      - NOTICE
      - WARNING
    Description: The alarm level of CloudWatch alarms
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  KinesisStreamName:
    Type: String
    AllowedPattern: .+
    Description: The Kinesis stream name [required]
  IteratorAgeMillisecondsThreshold:
    Type: Number
    Default: 30000
    MinValue: 0
    Description: The threshold of IteratorAgeMilliseconds [required]
  NumberOfPutRecordThreshold:
    Type: Number
    Default: 1000
    MinValue: 0
    Description: The threshold of PutRecord per minute [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]
  CreateNoticeAlarm: !Not [ !Equals [ !Ref AlarmLevel, WARNING ] ]

Resources:
  AlarmKinesisIteratorAgeMilliseconds:
    Condition: CreateNoticeAlarm
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Kinesis* (${KinesisStreamName}) で *GetRecords.IteratorAgeMillisecondsの値が増加* しています。これは、レコードを読み取る *アプリケーションの処理が遅延* していることを示しています。このエラーが継続する場合は、 *トラフィックの増大* もしくは *内部処理に異常が発生* している可能性があります。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Notice-${CustomAlarmName}-Kinesis-${KinesisStreamName}-IteratorAgeMilliseconds-is-Too-Long
        - !Sub Notice-Kinesis-${KinesisStreamName}-IteratorAgeMilliseconds-is-Too-Long
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: StreamName
          Value: !Ref KinesisStreamName
      EvaluationPeriods: 3
      MetricName: GetRecords.IteratorAgeMilliseconds
      Namespace: AWS/Kinesis
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: !Ref IteratorAgeMillisecondsThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmKinesisPutRecordSuccess:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Kinesis* (${KinesisStreamName}) で *入力レコード数が増加* しています。このエラーが継続する場合は、 *トラフィックが増大* している可能性があります。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Kinesis-${KinesisStreamName}-PutRecord-Success-is-Too-High
        - !Sub Warning-Kinesis-${KinesisStreamName}-PutRecord-Success-is-Too-High
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: StreamName
          Value: !Ref KinesisStreamName
      EvaluationPeriods: 1
      MetricName: PutRecord.Success
      Namespace: AWS/Kinesis
      OKActions:
        - !Ref SNSTopicArn
      # Alert when Sum is over 600000 msec in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: !Ref NumberOfPutRecordThreshold
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmKinesisWriteProvisionedThroughputExceeded:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Kinesis* (${KinesisStreamName}) で *スロットリングが発生* しています。これは、プロビジョニングされたスループット値を超えるリクエストが発生して、書き込み処理が中断されたことを示しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Kinesis-${KinesisStreamName}-WriteProvisionedThroughputExceeded
        - !Sub Warning-Kinesis-${KinesisStreamName}-WriteProvisionedThroughputExceeded
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: StreamName
          Value: !Ref KinesisStreamName
      EvaluationPeriods: 1
      MetricName: WriteProvisionedThroughputExceeded
      Namespace: AWS/Kinesis
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue