AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for AWS Elemental MediaStore

Metadata:
  AWS::ServerlessRepo::Application:
    Name: cloudwatch-alarm-about-mediastore
    Description: Create Amazon CloudWatch Alarm about AWS Elemental MediaStore.
    Author: Eiji KOMINAMI
    SpdxLicenseId: MIT
    LicenseUrl: s3://eijikominami-test/LICENSE
    ReadmeUrl: s3://eijikominami-test/readme/cloudwatch-alarm-about-mediastore.md
    Labels: []
    HomePageUrl: https://github.com/eijikominami/aws-cloudformation-templates
    SourceCodeUrl: https://github.com/eijikominami/aws-cloudformation-templates

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom alram name
  ContainerName:
    Type: String
    Default: ''
    Description: The container name   
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  AlarmPutRequestsThrottle:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*MediaStore* (${ContainerName}) の *PutRequestsでスロットリングが発生* しました。このエラーの詳細は、<https://docs.aws.amazon.com/mediastore/latest/ug/monitor-with-cloudwatch-metrics.html|Monitoring AWS Elemental MediaStore with Amazon CloudWatch metrics
> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-MediaStore-${ContainerName}-PutRequests-Throttle
        - !Sub Warning-MediaStore-${ContainerName}-PutRequests-Throttle
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ContainerName
          Value: !Ref ContainerName
        - Name: RequestType
          Value: PutRequests
      EvaluationPeriods: 1
      MetricName: ThrottleCount
      Namespace: AWS/MediaStore
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmListRequestsThrottle:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*MediaStore* (${ContainerName}) の *ListRequestsでスロットリングが発生* しました。このエラーの詳細は、<https://docs.aws.amazon.com/mediastore/latest/ug/monitor-with-cloudwatch-metrics.html|Monitoring AWS Elemental MediaStore with Amazon CloudWatch metrics
> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-MediaStore-${ContainerName}-ListRequests-Throttle
        - !Sub Warning-MediaStore-${ContainerName}-ListRequests-Throttle
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ContainerName
          Value: !Ref ContainerName
        - Name: RequestType
          Value: ListRequests
      EvaluationPeriods: 1
      MetricName: ThrottleCount
      Namespace: AWS/MediaStore
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AlarmDeleteRequestsThrottle:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*MediaStore* (${ContainerName}) の *DeleteRequestsスロットリングが発生* しました。このエラーの詳細は、<https://docs.aws.amazon.com/mediastore/latest/ug/monitor-with-cloudwatch-metrics.html|Monitoring AWS Elemental MediaStore with Amazon CloudWatch metrics
> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-MediaStore-${ContainerName}-DeleteRequests-Throttle
        - !Sub Warning-MediaStore-${ContainerName}-DeleteRequests-Throttle
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ContainerName
          Value: !Ref ContainerName
        - Name: RequestType
          Value: DeleteRequests
      EvaluationPeriods: 1
      MetricName: ThrottleCount
      Namespace: AWS/MediaStore
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue