AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Network Load Balancer

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  LoadBalancer:
    Type: String
    AllowedPattern: .+
    Description: The load balancer name [required]  
  TargetGroup:
    Type: String
    AllowedPattern: .+
    Description: The target group id [required]
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  UnHealthyHostCount:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Network Load Balancer* (${CustomAlarmName}) で *異常なホストが検出* されました。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html|Network Load Balancer の CloudWatch メトリクス> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-NLB-UnHealthyHostCount
        - Warning-NLB-UnHealthyHostCount
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancer
        - Name: TargetGroup
          Value: !Ref TargetGroup
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: UnHealthyHostCount
      Namespace: AWS/NetworkELB
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  PortAllocationErrorCount:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*Network Load Balancer* (${CustomAlarmName}) で *ポート割り当てエラー* が発生しました。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html|Network Load Balancer の CloudWatch メトリクス> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-NLB-PortAllocationErrorCount
        - Warning-NLB-PortAllocationErrorCount
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancer
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: PortAllocationErrorCount
      Namespace: AWS/NetworkELB
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue