AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for Amazon Route 53 Resolver

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  EndpointId:
    Type: String
    AllowedPattern: .+
    Description: The endpoint ID of the Route 53 Resolver [required]  
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  EndpointUnhealthyENICount:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: '*Route53 Resolver* に *復旧の必要のある ENI* があります。このエラーの詳細は、<https://docs.aws.amazon.com/ja_jp/Route53/latest/DeveloperGuide/monitoring-resolver-with-cloudwatch.html|Amazon CloudWatch による Route 53 Resolver エンドポイントのモニタリング> をご覧ください。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-Route53Resolver-${EndpointId}-EndpointUnhealthyENICount
        - !Sub Warning-Route53Resolver-${EndpointId}-EndpointUnhealthyENICount
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: EndpointId
          Value: !Ref EndpointId
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: EndpointUnhealthyENICount
      Namespace: AWS/Route53Resolver
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue