AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch alarm for AWS Certificate Manager Run Command

Parameters:
  CustomAlarmName:
    Type: String
    Default: ''
    Description: The custom Alram name
  SNSTopicArn:
    Type: String
    AllowedPattern: .+
    Description: The SNS topic ARN [required] 

Conditions:
  CreateCustomAlarmName: !Not [ !Equals [ !Ref CustomAlarmName, '' ] ]

Resources:
  SSMCommandsDeliveryTimedOut:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*SSM (RunCommand)* で *タイムアウト* が発生しています。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-SSM-DeliveryTimedOut
        - Warning-SSM-DeliveryTimedOut
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: CommandsDeliveryTimedOut
      Namespace: AWS/SSM-RunCommand
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching
  SSMCommandsCommandsFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopicArn
      AlarmDescription: !Sub '*SSM (RunCommand)* で *コマンド実行が失敗* しました。'
      AlarmName: !If
        - CreateCustomAlarmName
        - !Sub Warning-${CustomAlarmName}-SSM-CommandsFailed
        - Warning-SSM-CommandsFailed
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: CommandsFailed
      Namespace: AWS/SSM-RunCommand
      OKActions:
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching