AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/web-servers/apprunner creates AWS App Runner.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'ECS Configuration'
        Parameters: 
          - Cpu
          - ImageUri
          - Memory
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment
          - LogicalName
          - TagKey
          - TagValue

Parameters:
  Cpu:
    Type: Number
    Default: 1024
    Description: The number of cpu units reserved for the container [required]
  ImageUri:
    Type: String
    AllowedPattern: .+
    Description: The image used to start a container
  Memory:
    Type: String
    Default: 3072
    Description: The amount (in MiB) of memory to present to the container [required]
  LogicalName:
    Type: String
    Default: WebServers
    AllowedPattern: .+
    Description: The custom prefix name [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      AutoScalingConfigurationArn: !GetAtt AppRunnerAutoScalingConfiguration.AutoScalingConfigurationArn
      InstanceConfiguration: 
        Cpu: !Ref Cpu
        InstanceRoleArn: String
        Memory: !Ref Memory
      HealthCheckConfiguration: 
        HealthyThreshold: 1
        Interval: 10
        Protocol: TCP
        Timeout: 5
        UnhealthyThreshold: 5
      NetworkConfiguration: 
        EgressConfiguration: 
          EgressType: DEFAULT
        IngressConfiguration: 
          IsPubliclyAccessible: true
        IpAddressType: DUAL_STACK
      ServiceName: !Ref LogicalName
      SourceConfiguration: 
        AuthenticationConfiguration: 
          AccessRoleArn: 
        AutoDeploymentsEnabled: true
        ImageRepository: 
          ImageRepository
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  AppRunnerAutoScalingConfiguration:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: DefaultConfiguration
      MaxConcurrency: 100
      MaxSize: 25
      MinSize: 1
      Tags: 
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue 