AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/web-servers/autoscaling creates Auto Scaling Group and Application Load Balancer or Network Load Balancer.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'AutoScaling Configuration'
        Parameters: 
          - AutoScalingDesiredCapacity
          - AutoScalingMaxSize
          - EC2ImageId
          - EC2InstanceType
          - EC2IamInstanceProfileArn
          - EC2KeyName
          - EC2SecurityGroupId
          - EC2VolumeSize
          - VPCId
      - Label: 
          default: 'Elastic Load Balancer Configuration'
        Parameters: 
          - EipAllocationId1ForNLB
          - EipAllocationId2ForNLB
          - EipAllocationId3ForNLB
          - LoadBalancerType
          - Logging
          - LogBucketName
          - SubnetId1ForAutoScaling
          - SubnetId2ForAutoScaling
          - SubnetId3ForAutoScaling
          - SubnetId1ForNLB
          - SubnetId2ForNLB
          - SubnetId3ForNLB
      - Label: 
          default: 'Domain Configuration'
        Parameters:
          - ACMValidationMethod
          - ACMDomainName
          - DomainName
          - Route53HostedZoneId
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment
          - LogicalName
          - TagKey
          - TagValue

Parameters:
  ACMValidationMethod:
    Type: String
    Default: DNS
    AllowedValues:
      - DNS
      - EMAIL
    Description: The validation method that you own or control the domain [required]
  ACMDomainName:
    Type: String
    Default: ''
    Description: The domain name created by Certification Manager
  AutoScalingDesiredCapacity:
    Type: Number
    Default: 1
    MinValue: 0
    Description: AutoScaling Desired Capacity [required]
  AutoScalingMaxSize:
    Type: Number
    Default: 1
    MinValue: 0
    Description: AutoScaling Max Size [required]
  DomainName:
    Type: String
    Default: ''
    Description: The CNAME attached to Elastic Load Balancer
  EC2ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-03dceaabddff8067e
    AllowedPattern: ^ami-.+$
    Description: The EC2 Image Id [required]
  EC2InstanceType:
    Type: String
    Default: t3.micro
    Description: The EC2 Instance Type [required]
  EC2IamInstanceProfileArn:
    Type: String
    AllowedPattern: .+
    Description: The Instance Profile ARN to attach the instances [required]
  EC2KeyName:
    Type: String
    Default: ''
    Description: The Name of an existing EC2 KeyPair to enable SSH access to the instance
  EC2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The Security Group id to attach the instances [required]
  EC2VolumeSize:
    Type: Number
    Default: 8
    MinValue: 8
    Description: EC2 Volume Size [required]
  EipAllocationId1ForNLB:     
    Type: String 
    Default: ''
    Description: The Elastic Ip Allocation Id1 for Network LoadBalancer
  EipAllocationId2ForNLB:     
    Type: String 
    Default: ''
    Description: The Elastic Ip Allocation Id2 for Network LoadBalancer
  EipAllocationId3ForNLB:     
    Type: String 
    Default: ''
    Description: The Elastic Ip Allocation Id3 for Network LoadBalancer
  LogicalName:
    Type: String
    Default: WebServers
    AllowedPattern: .+
    Description: The custom prefix name [required]
  LogBucketName:
    Type: String
    Default: ''
    Description: The custom S3 bucket name for access logging [conditional]
  Logging:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable logging [required]
  LoadBalancerType:
    Type: String
    Default: application
    AllowedValues:
      - application
      - network
    Description: The LoadBalancer Type [required]
  Route53HostedZoneId:
    Type: String
    Default: ''
    Description: Route53 hosted zone id
  SubnetId1ForAutoScaling:
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: .+
    Description: The subnet id 1 for AutoScaling
  SubnetId2ForAutoScaling:
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: .+
    Description: The subnet id 2 for AutoScaling
  SubnetId3ForAutoScaling:
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: .+
    Description: The subnet id 3 for AutoScaling
  SubnetId1ForNLB:
    Type: AWS::EC2::Subnet::Id
    Default: ''
    Description: The subnet id 1 for Elastic Load Balancer
  SubnetId2ForNLB:
    Type: AWS::EC2::Subnet::Id
    Default: ''
    Description: The subnet id 2 for Elastic Load Balancer
  SubnetId3ForNLB:
    Type: AWS::EC2::Subnet::Id
    Default: ''
    Description: The subnet id 3 for Elastic Load Balancer
  SNSForAlertArn:
    Type: String
    Default: ''   
  SNSForDeploymentArn:
    Type: String
    Default: ''
  VPCId:
    Type: AWS::EC2::VPC::Id
    AllowedPattern: .+
    Description: VPC Id [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  KeyExists: !Not [ !Equals [ !Ref EC2KeyName, '' ] ]
  CreateCertificateManager: !Not [ !Equals [ !Ref ACMDomainName, ''] ]
  CreateLog: !Equals [ !Ref Logging, ENABLED ]
  CreateNetworkLoadBalancer: !Equals [ !Ref LoadBalancerType, network ]
  CreateRoute53: !And [ !Not [ !Equals [ !Ref Route53HostedZoneId, ''] ], !Not [ !Equals [ !Ref DomainName, ''] ] ]
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']

Resources:
  # Nested Stack
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.7
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.7
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # Service-linked Role
  ServiceLinkedRoleForAutoScaling:
    Type: AWS::IAM::ServiceLinkedRole
    Properties: 
      AWSServiceName: autoscaling.amazonaws.com
      CustomSuffix: !Ref LogicalName
      Description: Default Service-Linked Role enables access to AWS Services and Resources used or managed by Auto Scaling
  # ELB
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false
        - Key: idle_timeout.timeout_seconds
          Value: 180
        - !If
          - CreateLog
          - Key: access_logs.s3.enabled
            Value: true
          - !Ref AWS::NoValue
        - !If
          - CreateLog
          - Key: access_logs.s3.bucket
            Value: !Ref LogBucketName
          - !Ref AWS::NoValue
      Name: !Sub elb-${LogicalName}
      Scheme: !If 
        - CreateRoute53
        - internet-facing
        - internal
      SecurityGroups:
       - !Ref EC2SecurityGroupId
      # For Network Load Balaner
      SubnetMappings: !If
        - CreateNetworkLoadBalancer
        - - SubnetId: !Ref SubnetId1ForNLB
            AllocationId: !Ref EipAllocationId1ForNLB
          - SubnetId: !Ref SubnetId2ForNLB
            AllocationId: !Ref EipAllocationId2ForNLB
          - SubnetId: !Ref SubnetId3ForNLB
            AllocationId: !Ref EipAllocationId3ForNLB
        - !Ref AWS::NoValue
      # For Application Load Balaner
      Subnets: !If
        - CreateNetworkLoadBalancer
        - !Ref AWS::NoValue
        - - !Ref SubnetId1ForNLB
          - !Ref SubnetId2ForNLB
          - !Ref SubnetId3ForNLB
      Tags:
        - Key: Name
          Value: !Sub elb-${LogicalName}-${AWS::Region}
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      Type: !Ref LoadBalancerType
  LoadBalancerTargetGroupHttp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-302
      Name: !Sub target-${LogicalName}
      Port: 80
      Protocol: !If
        - CreateNetworkLoadBalancer
        - TCP
        - HTTP
      Tags:
        - Key: Name
          Value: !Sub target-${LogicalName}-${AWS::Region}
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPCId
  LoadBalancerListenerHttp:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
        - TargetGroupArn: !Ref LoadBalancerTargetGroupHttp
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: !If
        - CreateNetworkLoadBalancer
        - TCP
        - HTTP
  LoadBalancerListenerHttps:
    Condition: CreateCertificateManager
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref CertificateManager
      DefaultActions:
        - TargetGroupArn: !Ref LoadBalancerTargetGroupHttp
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: !If
        - CreateNetworkLoadBalancer
        - TLS
        - HTTPS
      # Default
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
  # Auto Scaling Group
  AutoScalingLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      AssociatePublicIpAddress: false
      BlockDeviceMappings: 
        - DeviceName: /dev/sda1
          Ebs: 
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: !Ref EC2VolumeSize
            VolumeType: gp3
      EbsOptimized: true
      IamInstanceProfile: !Ref EC2IamInstanceProfileArn
      ImageId: !Ref EC2ImageId
      InstanceMonitoring: true
      InstanceType: !Ref EC2InstanceType
      KeyName: !If
        - KeyExists
        - !Ref EC2KeyName
        - !Ref AWS::NoValue
      LaunchConfigurationName: !Sub autoscalinglaunchconfiguration-${LogicalName}
      MetadataOptions: 
        HttpEndpoint: enabled
        HttpPutResponseHopLimit: 1
        HttpTokens: required
      SecurityGroups: 
        - !Ref EC2SecurityGroupId
      UserData: !Base64
        Fn::Join:
          - ''
          - - |
              #!/bin/sh
            - >
              AWS_AVAIL_ZONE=$(curl
              http://169.254.169.254/latest/meta-data/placement/availability-zone)
            - |
              AWS_REGION=${AWS_AVAIL_ZONE::-1}
            - >
              AWS_INSTANCE_ID=$(curl
              http://169.254.169.254/latest/meta-data/instance-id)
            - >
              ROOT_VOLUME_IDS=$(aws ec2 describe-instances --region $AWS_REGION
              --instance-id $AWS_INSTANCE_ID --output text --query
              Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId)
            - !Sub >
              aws ec2 create-tags --resources $ROOT_VOLUME_IDS --region
              $AWS_REGION --tags Key=${TagKey},Value=${TagValue}
  AutoScalingGroup:
    DependsOn:
         - ServiceLinkedRoleForAutoScaling
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: !Sub autoscalinggroup-${LogicalName}
      Cooldown: '300'
      DesiredCapacity: !Ref AutoScalingDesiredCapacity
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName: !Ref AutoScalingLaunchConfiguration
      MaxSize: !Ref AutoScalingMaxSize
      MetricsCollection: 
        - Granularity: 1Minute
          Metrics:
            - GroupMinSize
            - GroupMaxSize
            - GroupDesiredCapacity
            - GroupInServiceInstances
            - GroupPendingInstances
            - GroupStandbyInstances
            - GroupTerminatingInstances
            - GroupTotalInstances
      MinSize: '1'
      NotificationConfigurations: 
        - NotificationTypes: 
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
            - autoscaling:TEST_NOTIFICATION
          TopicARN: !Ref SNSForAlertArn
      ServiceLinkedRoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_${LogicalName}
      Tags:
        - Key: environment
          PropagateAtLaunch: true
          Value: !Ref Environment
        - Key: !Ref TagKey
          PropagateAtLaunch: true
          Value: !Ref TagValue
      TargetGroupARNs:
        - !Join
          - ''
          - - !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:'
            - !GetAtt LoadBalancerTargetGroupHttp.TargetGroupFullName
      TerminationPolicies: 
        - Default
      VPCZoneIdentifier: 
        - !Ref SubnetId1ForAutoScaling
        - !Ref SubnetId2ForAutoScaling
        - !Ref SubnetId3ForAutoScaling
  # CertificateManager
  CertificateManager:
    Condition: CreateCertificateManager
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref ACMDomainName
      ValidationMethod: !Ref ACMValidationMethod
      DomainValidationOptions: !If
        - CreateRoute53
        - - DomainName: !Ref ACMDomainName
            HostedZoneId: !Ref Route53HostedZoneId
        - !Ref AWS::NoValue
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # Route53
  Route53RecordSet:
    Condition: CreateRoute53
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
      Comment: !Ref DomainName
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref DomainName
      # Alias record
      Type: A
  CloudWatchAlarmALBHttp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-application-elb
        SemanticVersion: 2.2.7
      NotificationARNs: 
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        CustomAlarmName: !Ref AWS::StackName
        LoadBalancer: !GetAtt LoadBalancer.LoadBalancerFullName
        SNSTopicArn: !If 
          - CreateSNSForAlert
          - !GetAtt SNSForAlert.Outputs.SNSTopicArn
          - !Ref SNSForAlertArn
        TargetGroup: !GetAtt LoadBalancerTargetGroupHttp.TargetGroupFullName
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
        
Outputs:
  LoadBalancerArn:
    Description: LoadBalancer ARN
    Value: !Ref LoadBalancer
  LoadBalancerDNSName:
    Description: LoadBalancer DNS Name
    Value: !GetAtt LoadBalancer.DNSName 