AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/static-web-hosting/az creates a VPC Subnet and related resources.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'AvailabilityZone Configuration'
        Parameters: 
          - AvailabilityZone
          - InternetGatewayId
          - NetworkLoadBalancer
          - SubnetPublicCidrBlock
          - SubnetExternalCidrBlock
          - VPCId
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalNamePrefix
          - TagKey
          - TagValue

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    AllowedPattern: .+
    Description: The Availability Zone name [required]
  InternetGatewayId:
    Type: String
    AllowedPattern: .+
    Description: The Internet Gateway Id [required]
  NetworkLoadBalancer:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable Network LoadBalaner [required]
  LogicalNamePrefix:
    Type: String
    Default: WebServers
    AllowedPattern: .+
    Description: The custom prefix name [required]
  SNSForAlertArn:
    Type: String
    AllowedPattern: .+
  SNSForDeploymentArn:
    Type: String
    AllowedPattern: .+
  SubnetPublicCidrBlock:
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: ^[0-9./]*$
    Description: The Public subnet CIDR block [required]
  SubnetExternalCidrBlock:
    Type: String
    AllowedPattern: ^[0-9./]*$
    Description: The private subnet CIDR block
  VPCId:
    Type: String
    AllowedPattern: .+
    Description: The VPC id [required]
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  PrivateSubnetExists:
    !Not [ !Equals [ !Ref SubnetExternalCidrBlock, '' ] ]
  NetworkLoadBalancerExists:
    !Equals [ !Ref NetworkLoadBalancer, ENABLED ]

Resources:
  # Subnet
  SubnetExternal:
    Condition: PrivateSubnetExists
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref SubnetExternalCidrBlock
      Tags:
        - Key: Name
          Value: !Sub subnet-${LogicalNamePrefix}-${AvailabilityZone}-ext
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VpcId: !Ref VPCId
  SubnetPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref SubnetPublicCidrBlock
      Tags:
        - Key: Name
          Value: !Sub subnet-${LogicalNamePrefix}-${AvailabilityZone}-pub
        - Key: !Ref TagKey
          Value: !Ref TagValue
      VpcId: !Ref VPCId
  # Route Table
  RouteTableExternal:
    Condition: PrivateSubnetExists
    Type: 'AWS::EC2::RouteTable'
    Properties: 
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub rtb-${LogicalNamePrefix}-${AvailabilityZone}-ext
        - Key: !Ref TagKey
          Value: !Ref TagValue
  RouteExternalToNATGateway:
    Condition: PrivateSubnetExists
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
      RouteTableId: !Ref RouteTableExternal
  RouteTablePublic:
    Type: 'AWS::EC2::RouteTable'
    Properties: 
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub rtb-${LogicalNamePrefix}-${AvailabilityZone}-pub
        - Key: !Ref TagKey
          Value: !Ref TagValue
  RoutePublicToInternetGateway:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewayId
      RouteTableId: !Ref RouteTablePublic
  RouteTableExternalAssociation:
    Condition: PrivateSubnetExists
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties: 
      RouteTableId: !Ref RouteTableExternal
      SubnetId: !Ref SubnetExternal
  RouteTablePublicAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties: 
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublic
  # Elastic IP
  EIPForNatGateway:
    Condition: PrivateSubnetExists
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub eip-${LogicalNamePrefix}-${AvailabilityZone}-natgateway
        - Key: !Ref TagKey
          Value: !Ref TagValue
  EIPForNLB:
    Condition: NetworkLoadBalancerExists
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub eip-${LogicalNamePrefix}-${AvailabilityZone}-nlb
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # NatGateway
  NatGateway:
    Condition: PrivateSubnetExists
    Type: 'AWS::EC2::NatGateway'
    Properties: 
      AllocationId: !GetAtt EIPForNatGateway.AllocationId
      SubnetId: !Ref SubnetPublic
      Tags: 
        - Key: Name
          Value: !Sub nat-${LogicalNamePrefix}-${AvailabilityZone}
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # CloudWatch Alarm
  CloudWatchAlarmNATGateway:
    Type: 'AWS::Serverless::Application'
    Properties:
      Parameters:
        CustomAlarmName: !Ref AWS::StackName
        SNSTopicArn: !Ref SNSForAlertArn
      NotificationARNs: 
        - !Ref SNSForDeploymentArn
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/cloudwatch-alarm-about-natgateway
        SemanticVersion: 1.2.3
      Tags:
        createdby: !Ref TagValue
Outputs:
  SubnetId:
    Description: Subnet ID
    Value: !Ref SubnetPublic
  NetworkLoadBalancerIPAllocationId:
    Condition: NetworkLoadBalancerExists
    Description: Internet GW IP address
    Value: !GetAtt EIPForNLB.AllocationId
  NetworkLoadBalancerIP:
    Condition: NetworkLoadBalancerExists
    Description: Internet GW IP address
    Value: !Ref EIPForNLB
  NatGatewayIP:
    Condition: PrivateSubnetExists
    Description: NAT GW IP address
    Value: !Ref EIPForNatGateway