AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description:  AWSCloudFormationTemplates/web-servers/cicd creates a CodePipeline pipeline to deploy artifacts to Amazon EC2.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Source Configuration'
        Parameters:
          - DockerFilePath
          - GitHubOwnerName
          - GitHubRepoName
          - GitHubBranchName
      - Label: 
          default: 'Build Configuration'
        Parameters:
          - CodeBuildImageName
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - CodeStarConnectionArn
      - Label: 
          default: 'Tag Configuration'
        Parameters: 
          - TagKey
          - TagValue

Parameters:
  CodeBuildImageName:
    Type: String
    Default: aws/codebuild/amazonlinux2-aarch64-standard:2.0
    AllowedPattern: ^aws/codebuild/amazonlinux2-.+$
    Description: The Docker image name for CodeBuild [required]
  CodeStarConnectionArn:
    Type: String
    Default: ''
    Description: The Amazon Resource Name (ARN) of the CodeStar connection
  DockerFilePath:
    Type: String
    AllowedPattern: .+
    Description: The path of Dockerfile
  GitHubOwnerName:
    Type: String
    AllowedPattern: .+
    Description: The GitHub owner name
  GitHubRepoName:
    Type: String
    AllowedPattern: .+
    Description: The GitHub repository name
  GitHubBranchName:
    Type: String
    Default: master
    AllowedPattern: .+
    Description: The Branch name of GitHub [required]
  LogicalName:
    Type: String
    Default: web-servers
    AllowedPattern: ^[a-z0-9][a-z0-9//.//-]*[a-z0-9]$
    Description: The custom prefix name [required]
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateCodeStarConnection: !Equals [ !Ref CodeStarConnectionArn, '']
  Development: !Equals [ !Ref GitHubBranchName, develop]

Resources:
  # IAM
  IAMRoleForCodeBuild:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Description: A role required for CodeBuild to access CodeBuild, S3 and CloudWatch Logs.
      Policies:
        - PolicyName: CodeBuild
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Required for `sam build`
              - Action:
                  - iam:ListPolicies
                Resource: '*'
                Effect: Allow
              # Default Policy
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
                Effect: Allow
              - Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub arn:aws:s3:::${S3ForArtifact}
                  - !Sub arn:aws:s3:::${S3ForArtifact}/*
                Effect: Allow
              - Action:
                  - serverlessrepo:SearchApplications
                  - serverlessrepo:GetApplication
                  - serverlessrepo:GetCloudFormationTemplate
                  - serverlessrepo:CreateCloudFormationTemplate
                  - serverlessrepo:CreateCloudFormationChangeSet
                  - serverlessrepo:ListApplicationVersions
                  - serverlessrepo:ListApplicationDependencies
                Resource: '*'
                Effect: Allow
              - Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${AWS::StackName}-*
                Effect: Allow
              - Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
                Effect: Allow
              - Action:
                  - ecr:ListImages
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetRepositoryPolicy
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: !GetAtt ECR.Arn
                Effect: Allow
      RoleName: !Sub CICD-CodeBuild-${AWS::Region}
      Tags:
        - Key: environment
          Value: !If
            - Development
            - development
            - production
        - Key: !Ref TagKey
          Value: !Ref TagValue
  IAMRoleForCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com 
            Action: sts:AssumeRole
      Description: A role required for CodePipeline to access related resources.
      Policies:
        - PolicyName: CodePipeline
          PolicyDocument:
            Version: 2012-10-17
            Statement:           
              # Default Policy
              - Action:
                  - iam:PassRole
                Resource: '*'
                Effect: Allow
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
                      - ecs-tasks.amazonaws.com
              - Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource: '*'
                Effect: Allow
              - Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplication
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource: '*'
                Effect: Allow
              - Action:
                  - codestar-connections:UseConnection
                Resource: '*'
                Effect: Allow
              - Action:
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                Resource: '*'
                Effect: Allow
              - Action:
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                Resource: '*'
                Effect: Allow
              - Action:
                  - opsworks:CreateDeployment
                  - opsworks:DescribeApps
                  - opsworks:DescribeCommands
                  - opsworks:DescribeDeployments
                  - opsworks:DescribeInstances
                  - opsworks:DescribeStacks
                  - opsworks:UpdateApp
                  - opsworks:UpdateStack
                Resource: '*'
                Effect: Allow
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                Resource: '*'
                Effect: Allow
              - Action:
                  - serverlessrepo:SearchApplications
                  - serverlessrepo:GetApplication
                  - serverlessrepo:GetCloudFormationTemplate
                  - serverlessrepo:CreateCloudFormationTemplate
                  - serverlessrepo:CreateCloudFormationChangeSet
                  - serverlessrepo:ListApplicationVersions
                  - serverlessrepo:ListApplicationDependencies
                Resource: '*'
                Effect: Allow
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: '*'
                Effect: Allow
              - Action:
                  - devicefarm:ListProjects
                  - devicefarm:ListDevicePools
                  - devicefarm:GetRun
                  - devicefarm:GetUpload
                  - devicefarm:CreateUpload
                  - devicefarm:ScheduleRun
                Resource: '*'
                Effect: Allow
              - Action:
                  - servicecatalog:ListProvisioningArtifacts
                  - servicecatalog:CreateProvisioningArtifact
                  - servicecatalog:DescribeProvisioningArtifact
                  - servicecatalog:DeleteProvisioningArtifact
                  - servicecatalog:UpdateProduct
                Resource: '*'
                Effect: Allow
              - Action:
                  - cloudformation:ValidateTemplate
                Resource: '*'
                Effect: Allow
              - Action:
                  - ecr:DescribeImages
                Resource: '*'
                Effect: Allow
      RoleName: !Sub ${AWS::StackName}-CodePipeline-${AWS::Region}
      Tags:
        - Key: environment
          Value: !If
            - Development
            - development
            - production
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # Container
  ECR:
    Type: AWS::ECR::Repository
    Properties: 
      EmptyOnDelete: false
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: web-servers
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # CodeStar Connection
  CodeStarConnection:
    Condition: CreateCodeStarConnection
    Type: AWS::CodeStarConnections::Connection
    Properties: 
      ConnectionName: !Sub GitHub-${AWS::StackName}
      ProviderType: GitHub
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # CodeBuild
  CodeBuildForContainer:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub Builds a container image of ${GitHubOwnerName}/${GitHubRepoName}
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImageName
        PrivilegedMode: true
        Type: ARM_CONTAINER
      LogsConfig: 
        CloudWatchLogs: 
          GroupName: !Ref CodeBuildLogGroupV2
          Status: ENABLED
      Name: !Sub ${AWS::StackName}-Container
      ServiceRole: !GetAtt IAMRoleForCodeBuild.Arn
      Source:
        BuildSpec: buildspec-container.yml
        Type: CODEPIPELINE
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TimeoutInMinutes: 60
  # CodePipeline
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStores:
        - ArtifactStore: 
            Location: !Ref S3ForArtifact
            Type: S3
          Region: !Ref AWS::Region
      Name: !Sub Container-${AWS::StackName}
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt IAMRoleForCodePipeline.Arn
      Stages: 
        # Source
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !If
                  - CreateCodeStarConnection
                  - !GetAtt CodeStarConnection.ConnectionArn
                  - !Ref CodeStarConnectionArn
                FullRepositoryId: !Sub ${GitHubOwnerName}/${GitHubRepoName}
                BranchName: !Ref GitHubBranchName
              Name: Container
              OutputArtifacts: 
                - Name: Source_Container
              RunOrder: 1
          Name: Source
        # Build
        - Actions:
            - ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                EnvironmentVariables: !Join
                  - ''
                  - - !Sub '[{"name": "REPOSITORY_URI", "value": "'
                    - !GetAtt ECR.RepositoryUri
                    - !Sub '"}, {"name": "DOCKER_FILE", "value": "${DockerFilePath}", "type": "PLAINTEXT"}]'
                PrimarySource: Source_CloudFormationTemplatesArtifact
                ProjectName: !Ref CodeBuildForContainer
              InputArtifacts:
                - Name: Source_Container
              Name: Container
              OutputArtifacts: 
                - Name: BuildArtifact_Container
              RunOrder: 1
          Name: Build
      Tags:
        - Key: environment
          Value: !If
            - Development
            - development
            - production
        - Key: !Ref TagKey
          Value: !Ref TagValue
      PipelineType: V2
  S3ForArtifact:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub cicd-artifact-${LogicalName}-${AWS::Region}-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationInDays
            ExpirationInDays: 7
            Status: Enabled
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: !If
            - Development
            - development
            - production
        - Key: !Ref TagKey
          Value: !Ref TagValue
  S3BucketPolicyForArtifact:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3ForArtifact
      PolicyDocument:
        Version: 2012-10-17
        Id: !Ref S3ForArtifact
        Statement:
          - Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !GetAtt S3ForArtifact.Arn
              - !Join
                - ''
                - - !GetAtt S3ForArtifact.Arn
                  - /*
            Condition:
              Bool: 
                aws:SecureTransport: false
  # CloudWatch Logs
  CodeBuildLogGroupV2:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupClass: INFREQUENT_ACCESS
      LogGroupName: !Sub /aws/codebuild/${AWS::StackName}_V2
      RetentionInDays: 60
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue

Outputs:
  RepositoryUri:
    Description: Repository URI for WebServers
    Value: !GetAtt ECR.RepositoryUri