AWSTemplateFormatVersion: 2010-09-09
Description: AWSCloudFormationTemplates/web-servers/dlm creates a DataLifecycleManager.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Data Lifecycle Manager Configuration'
        Parameters: 
          - DailySnapshotScheduledAt
          - SnapshotInterval
          - SnapshotRetainRule
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalName
          - Environment
          - TagKey
          - TagValue

Parameters:
  DailySnapshotScheduledAt:
    Type: String
    Default: '17:00'
    AllowedPattern: ^[0-1][0-9]:[0-9][0-9]$
    Description: Daily Snapshot time (HH:MM) [required]
  LogicalName:
    Type: String
    Default: WebServers
    AllowedPattern: .+
    Description: The custom prefix name [required]
  SnapshotInterval:
    Type: Number
    Default: 24
    AllowedValues:
      - 2
      - 3
      - 4 
      - 6
      - 8
      - 12
      - 24
    Description: The interval between snapshots [required]
  SnapshotRetainRule:
    Type: Number
    Default: 7
    MinValue: 1
    Description: The number of snapshots to retain for each volume [required]
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Resources:
  # IAM
  IAMRoleForDLM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: dlm.amazonaws.com
            Action: sts:AssumeRole
      Description: A role required for DLM.
      Policies:
        - PolicyName: EC2Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateSnapshot
                  - ec2:CreateSnapshots
                  - ec2:DeleteSnapshot
                  - ec2:DescribeVolumes
                  - ec2:DescribeInstances
                  - ec2:DescribeSnapshots
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                Resource: 'arn:aws:ec2:*::snapshot/*'
      RoleName: !Sub ${LogicalName}-DataLifecycleManager-${AWS::Region}
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # DLM
  DataLifecycleManager:
    Type: AWS::DLM::LifecyclePolicy
    Properties: 
      Description: Lifecycle Policy
      ExecutionRoleArn: !GetAtt IAMRoleForDLM.Arn
      PolicyDetails: 
        ResourceTypes: 
          - VOLUME
        Schedules:
          - CopyTags: true
            CreateRule:
              Interval: !Ref SnapshotInterval
              IntervalUnit: HOURS
              Times:
                - !Ref DailySnapshotScheduledAt
            Name: Daily Snapshots
            RetainRule:
              Count: !Ref SnapshotRetainRule
        TargetTags: 
          - Key: environment
            Value: !Ref Environment
          - Key: !Ref TagKey
            Value: !Ref TagValue
      State: ENABLED