AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationTemplates/web-servers/ssm executes Systems Manager Quick Setup and creates a Systems Manager Maintenance Window and related resources.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Systems Manager Configuration'
        Parameters: 
          - IgnoreResourceConflicts
          - PatchingAt
      - Label: 
          default: 'Notification Configuration'
        Parameters: 
          - SNSForAlertArn
          - SNSForDeploymentArn
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - LogicalNamePrefix
          - TagKey
          - TagValue

Parameters:
  IgnoreResourceConflicts:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED  
  PatchingAt:
    Type: Number
    Default: 3
    MinValue: 0
    MaxValue: 23
    Description: Daily patching time (H) [required]
  LogicalNamePrefix:
    Type: String
    Default: WebServers
    Description: The custom prefix name [required]
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: The Amazon SNS topic ARN for alert
  SNSForDeploymentArn:
    Type: String
    Default: '' 
    Description: The Amazon SNS topic ARN for deployment information
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-templates
    AllowedPattern: .+

Conditions:
  CreateResource: !Equals [ !Ref IgnoreResourceConflicts, DISABLED ]
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']

Resources:
  # Nested Stack
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 1.3.8
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 1.3.8
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  # Service-linked Role
  ServiceLinkedRoleForSSM:
    Type: 'AWS::IAM::ServiceLinkedRole'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties: 
      AWSServiceName: ssm.amazonaws.com
      Description: Provides access to AWS Resources managed or used by Amazon SSM.
  # IAM Role
  IAMRoleForEC2:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Description: A role required for Managed Instances.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      RoleName: !Sub '${LogicalNamePrefix}-EC2SSMRole-${AWS::Region}'
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # InstanceProfile
  IamInstanceProfileForIAMRoleForEC2:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Ref IAMRoleForEC2
      Roles: 
        - !Ref IAMRoleForEC2
  # Document
  CloudWatchAgentInstallAndConfigure:
    Type: 'AWS::SSM::Document'
    Properties: 
      Content:
        schemaVersion: '2.2'
        description: A composite document for installing and configuring CloudWatchAgent.
        mainSteps:
          - name: installCWAgent
            action: aws:runDocument
            inputs:
              documentType: SSMDocument
              documentPath: AWS-ConfigureAWSPackage
              documentParameters:
                action: Install
                name: AmazonCloudWatchAgent
          - name: second
            action: aws:runDocument
            inputs:
              documentType: SSMDocument
              documentPath: AmazonCloudWatch-ManageAgent
              documentParameters:
                action: configure
                mode: ec2
                optionalConfigurationSource: default
                optionalRestart: yes
      DocumentType: Command
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudWatchAgentUpdate:
    Type: 'AWS::SSM::Document'
    Properties: 
      Content:
        schemaVersion: '2.2'
        description: A composite document for updating CloudWatchAgent.
        mainSteps:
          - name: first
            action: aws:runShellScript
            inputs:
              runCommand:
                - sleep 1800
            precondition:
              StringEquals:
                - platformType
                - Linux
          - name: second
            action: aws:runPowerShellScript
            inputs:
              runCommand:
                - Start-Sleep –Seconds 1800
            precondition:
              StringEquals:
                - platformType
                - Linux
          - name: installCWAgent
            action: aws:runDocument
            inputs:
              documentType: SSMDocument
              documentPath: AWS-ConfigureAWSPackage
              documentParameters:
                action: Install
                name: AmazonCloudWatchAgent
      DocumentType: Command
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  # State Manager
  # Install and configure the CloudWatch agent
  SystemAssociationForInstallAndConfigureCloudWatchAgent:
    Type: 'AWS::SSM::Association'
    Properties: 
      AssociationName: SystemAssociationForInstallAndConfigureCloudWatchAgent
      Name: !Ref CloudWatchAgentInstallAndConfigure
      Targets: 
        - Key: !Sub tag:${TagKey}
          Values:
            - !Sub value:${TagValue}
  # Update Systems Manager (SSM) Agent every two weeks
  SystemAssociationForSsmAgentUpdate:
    Type: 'AWS::SSM::Association'
    Properties: 
      AssociationName: SystemAssociationForSsmAgentUpdate
      Name: AWS-UpdateSSMAgent
      ScheduleExpression: rate(14 days)
      Targets: 
        - Key: !Sub tag:${TagKey}
          Values:
            - !Sub value:${TagValue}
  # Collect inventory from your instances every 30 minutes
  SystemAssociationForInventoryCollection:
    Condition: CreateResource
    Type: 'AWS::SSM::Association'
    Properties: 
      AssociationName: SystemAssociationForInventoryCollection
      Name: AWS-GatherSoftwareInventory
      Parameters:
          applications:
            - Enabled
          awsComponents:
            - Enabled
          customInventory:
            - Enabled
          instanceDetailedInformation:
            - Enabled
          networkConfig:
            - Enabled
          services:
            - Enabled
          windowsRoles:
            - Enabled
          windowsUpdates:
            - Enabled
      ScheduleExpression: rate(30 minutes)
      Targets: 
        - Key: !Sub tag:${TagKey}
          Values:
            - !Sub value:${TagValue}
  # Scan instances for missing patches daily
  SystemAssociationForScanningPatches:
    Type: 'AWS::SSM::Association'
    Properties: 
      AssociationName: SystemAssociationForScanningPatches
      Name: AWS-RunPatchBaseline
      ScheduleExpression: rate(1 day)
      Parameters:
          Operation:
            - Scan
      Targets: 
        - Key: !Sub tag:${TagKey}
          Values:
            - !Sub value:${TagValue}
  # Update the CloudWatch agent every 30 days
  SystemAssociationForUpdateCloudWatchAgent:
    Type: 'AWS::SSM::Association'
    Properties: 
      AssociationName: SystemAssociationForUpdateCloudWatchAgent
      Name: !Ref CloudWatchAgentUpdate
      ScheduleExpression: rate(30 days)
      Targets: 
        - Key: !Sub tag:${TagKey}
          Values:
            - !Sub value:${TagValue}
  # Install the Inspector agent two weeks
  SystemAssociationForAmazonInspector:
    Type: 'AWS::SSM::Association'
    Properties: 
      AssociationName: SystemAssociationForAmazonInspector
      Name: AmazonInspector-ManageAWSAgent
      ScheduleExpression: rate(14 days)
      Parameters:
          Operation:
            - Install
      Targets: 
        - Key: !Sub tag:${TagKey}
          Values:
            - !Sub value:${TagValue}
  # Maintenance Window
  MaintenanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Properties: 
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: !Sub Patching to ${LogicalNamePrefix} EC2 instances at ${PatchingAt}:00 every day.
      Duration: 2
      Name: DailyMaintenance
      Schedule: !Sub cron(0 ${PatchingAt} * * ? *)
      ScheduleTimezone: Asia/Tokyo
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
  MaintenanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties: 
      Description: !Sub EC2 instances createdby ${LogicalNamePrefix}.
      Name: !Ref LogicalNamePrefix
      ResourceType: INSTANCE
      Targets:
        - Key: !Join
          - ':'
          - - tag
            - !Ref TagKey
          Values:
            - !Ref TagValue
      WindowId: !Ref MaintenanceWindow
  MaintenanceWindowTask:
    DependsOn:
      - ServiceLinkedRoleForSSM
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties: 
      Description: !Sub Patching for ${LogicalNamePrefix} EC2 instances.
      MaxConcurrency: '50'
      MaxErrors: '0'
      Name: !Sub PatchingTaskFor${LogicalNamePrefix}
      Priority: 0
      ServiceRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM
      Targets:  
        - Key: WindowTargetIds
          Values: 
            - !Ref MaintenanceWindowTarget
      TaskArn: AWS-RunPatchBaseline
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          NotificationConfig:
              NotificationArn: !If
                - CreateSNSForAlert
                - !GetAtt SNSForAlert.Outputs.SNSTopicArn
                - !Ref SNSForAlertArn
          Parameters: 
            Operation:
              - Install
          ServiceRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM
          TimeoutSeconds: 600
      TaskType: RUN_COMMAND
      WindowId: !Ref MaintenanceWindow
  EventBridgeForSSM:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Systems Manager created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ssm
        detail-type: 
          - EC2 Command Status-change Notification
          - EC2 Command Invocation Status-change Notification
          - EC2 Automation Step Status-change Notification
          - EC2 Automation Execution Status-change Notification
          - EC2 State Manager Association State Change
          - EC2 State Manager Instance Association State Change
        detail:
          status: 
            - Failed
      Name: SystemsManager
      State: ENABLED
      Targets:
        - Arn: !If
            - CreateSNSForAlert
            - !GetAtt SNSForAlert.Outputs.SNSTopicArn
            - !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForSSMConfigurationCompliance:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Systems Manager Configuration Compliance created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ssm
        detail-type: 
          - Configuration Compliance State Change
        # EC2 only
        detail:
          resource-id:
            - prefix: i-
      Name: SystemsManagerConfigurationCompliance
      State: ENABLED
      Targets:
        - Arn: !If
            - CreateSNSForAlert
            - !GetAtt SNSForAlert.Outputs.SNSTopicArn
            - !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForSSMMaintenanceWindow:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Systems Manager Maintenance Window created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ssm
        detail-type: 
          - Maintenance Window Target Registration Notification
        detail:
          status:
            - CANCELLED 
            - CANCELLING 
            - FAILED 
            - SKIPPED_OVERLAPPING 
            - TIMED_OUT
      Name: SystemsManagerMaintenanceWindow
      State: ENABLED
      Targets:
        - Arn: !If
            - CreateSNSForAlert
            - !GetAtt SNSForAlert.Outputs.SNSTopicArn
            - !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForSSMParameterStore:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Systems Manager Parameter Store created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ssm
        detail-type: 
          - Parameter Store Change
      Name: SystemsManagerParameterStore
      State: ENABLED
      Targets:
        - Arn: !If
            - CreateSNSForAlert
            - !GetAtt SNSForAlert.Outputs.SNSTopicArn
            - !Ref SNSForAlertArn
          Id: SNSForAlert